# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\ventanas\ventanas_qt\VentanaPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventanaPrincipal(object):
    def setupUi(self, ventanaPrincipal):
        ventanaPrincipal.setObjectName("ventanaPrincipal")
        ventanaPrincipal.resize(1206, 722)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ventanaPrincipal.sizePolicy().hasHeightForWidth())
        ventanaPrincipal.setSizePolicy(sizePolicy)
        ventanaPrincipal.setMaximumSize(QtCore.QSize(1206, 722))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconos/iconos/icono-app-dgtic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ventanaPrincipal.setWindowIcon(icon)
        ventanaPrincipal.setStyleSheet("\n"
"#ventanaPrincipal {\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.477612 rgba(72, 111, 182, 255), stop:0.751244 rgba(31, 72, 133, 255))\n"
"}\n"
"\n"
"\n"
"/* PÁGINA DE INICIAR SESIÓN */\n"
"\n"
"#frameCamposInicioSesion {\n"
"    background-color: rgb(229, 229, 229);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#labelTituloIniciarSesion {\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#labelNombreUsuario,\n"
"#labelClaveUsuario {\n"
"    font-size: 17px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QWidget{\n"
"    font: 9.5pt \"Segoe UI\";\n"
"}\n"
"\n"
"#botonAcceder{\n"
"    font: 8pt \"Segoe UI Black\";\n"
"    color: #ffffff;\n"
"    background-color: #004aad;\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"    padding-bottom: 2px;\n"
"}\n"
"\n"
"#botonAcceder::hover{\n"
"    background-color: #5c8bc9;\n"
"}\n"
"\n"
"#botonAcceder::pressed{\n"
"    background-color: #063c85;\n"
"}\n"
"\n"
"\n"
"\n"
"/* PÁGINA APP*/\n"
"\n"
"#frameApp{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid #000000;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"#frameInferior .QPushButton{\n"
"    color: #ffffff;\n"
"    background-color: #417fd2;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"    padding-bottom: 2px;\n"
"    font: 8.5pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"#frameInferior .QPushButton::hover{\n"
"    background-color: #5c8bc9;\n"
"}\n"
"\n"
"#frameInferior .QPushButton::pressed{\n"
"    background-color: #063c85;\n"
"}\n"
"\n"
"#frameSuperior .QToolButton{\n"
"    color: #ffffff;\n"
"    background-color: #417fd2;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    border-radius: 2px;\n"
"    padding-bottom: 2px;\n"
"    font: 9pt \"Segoe UI\";\n"
"}\n"
"\n"
"#frameSuperior .QToolButton::hover{\n"
"    background-color: #5c8bc9;\n"
"}\n"
"\n"
"#frameSuperior .QToolButton::pressed{\n"
"    background-color: #063c85;\n"
"}\n"
"\n"
"\n"
"#frameSuperior .QPushButton{\n"
"    color: #ffffff;\n"
"    background-color: #417fd2;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    border-radius: 6px;\n"
"    padding-bottom: 2px;\n"
"    font: 8.5pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"#frameSuperior .QPushButton::hover{\n"
"    background-color: #5c8bc9;\n"
"}\n"
"\n"
"#frameSuperior .QPushButton::pressed{\n"
"    background-color: #063c85;\n"
"}\n"
"\n"
"#frameSuperior #botonRefrescarApp{\n"
"    background-color: #c8c8c8;\n"
"}\n"
"\n"
"\n"
"#frameSuperior #botonRefrescarApp::hover{\n"
"    background-color: #dadada;\n"
"}\n"
"\n"
"#frameSuperior #botonRefrescarApp::pressed{\n"
"    background-color: #a3a3a3;\n"
"}\n"
"\n"
"\n"
"\n"
"/* PÁGINA DEPARTAMENTOS*/\n"
"\n"
"#frameGeneralDepartamentos{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid #000000;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"#frameSeccionRegistrarDepartamento .QPushButton,\n"
"#frameInferiorSeccionDepartamentos .QPushButton {\n"
"    color: #ffffff;\n"
"    background-color: #417fd2;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    border-radius: 6px;\n"
"    padding-bottom: 2px;\n"
"    font: 8.5pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"#frameSeccionRegistrarDepartamento .QPushButton::hover,\n"
"#frameInferiorSeccionDepartamentos .QPushButton::hover{\n"
"    background-color: #5c8bc9;\n"
"}\n"
"\n"
"#frameSeccionRegistrarDepartamento .QPushButton::pressed,\n"
"#frameInferiorSeccionDepartamentos .QPushButton::pressed{\n"
"    background-color: #063c85;\n"
"}\n"
"\n"
"#labelTituloRegistrarDepartamento {\n"
"    font-weight: bold;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"#frameSeccionRegistrarDepartamento #botonRefrescarDepartamentos{\n"
"    background-color: #c8c8c8;\n"
"}\n"
"\n"
"#frameSeccionRegistrarDepartamento #botonRefrescarDepartamentos::hover{\n"
"    background-color: #dadada;\n"
"}\n"
"\n"
"#frameSeccionRegistrarDepartamento #botonRefrescarDepartamentos::pressed{\n"
"    background-color: #a3a3a3;\n"
"}\n"
"\n"
"\n"
"\n"
"/* PÁGINA USUARIOS*/\n"
"\n"
"#frameGeneralUsuarios{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid #000000;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"#frameSeccionRegistrarUsuario .QPushButton,\n"
"#frameInferiorSeccionUsuarios .QPushButton {\n"
"    color: #ffffff;\n"
"    background-color: #417fd2;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    border-radius: 6px;\n"
"    padding-bottom: 2px;\n"
"    font: 8.5pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"#labelTituloRegistrarUsuario {\n"
"    font-weight: bold;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"#frameSeccionRegistrarUsuario .QPushButton::hover,\n"
"#frameInferiorSeccionUsuarios .QPushButton::hover{\n"
"    background-color: #5c8bc9;\n"
"}\n"
"\n"
"#frameSeccionRegistrarUsuario .QPushButton::pressed,\n"
"#frameInferiorSeccionUsuarios .QPushButton::pressed{\n"
"    background-color: #063c85;\n"
"}\n"
"\n"
"#frameSeccionRegistrarUsuario #botonRefrescarUsuarios{\n"
"    background-color: #c8c8c8;\n"
"}\n"
"\n"
"#frameSeccionRegistrarUsuario #botonRefrescarUsuarios::hover{\n"
"    background-color: #dadada;\n"
"}\n"
"\n"
"#frameSeccionRegistrarUsuario #botonRefrescarUsuarios::pressed{\n"
"    background-color: #a3a3a3;\n"
"}\n"
"\n"
"\n"
"\n"
"/* PÁGINA TIPO DE SERVICIO*/\n"
"\n"
"#frameGeneralTipoServicio{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid #000000;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"#frameSuperiorTipoServicio .QPushButton,\n"
"#frameInferiorTipoServicio .QPushButton {\n"
"    color: #ffffff;\n"
"    background-color: #417fd2;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    border-radius: 6px;\n"
"    padding-bottom: 2px;\n"
"    font: 8.5pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"#labelTituloRegistrarTipoServicio {\n"
"    font-weight: bold;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"#frameSuperiorTipoServicio .QPushButton::hover,\n"
"#frameInferiorTipoServicio .QPushButton::hover{\n"
"    background-color: #5c8bc9;\n"
"}\n"
"\n"
"#frameSuperiorTipoServicio .QPushButton::pressed,\n"
"#frameInferiorTipoServicio .QPushButton::pressed{\n"
"    background-color: #063c85;\n"
"}\n"
"\n"
"#frameSuperiorTipoServicio #botonRefrescarTiposServicio{\n"
"    background-color: #c8c8c8;\n"
"}\n"
"\n"
"#frameSuperiorTipoServicio #botonRefrescarTiposServicio::hover{\n"
"    background-color: #dadada;\n"
"}\n"
"\n"
"#frameSuperiorTipoServicio #botonRefrescarTiposServicio::pressed{\n"
"    background-color: #a3a3a3;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ventanaPrincipal)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ventanas = QtWidgets.QStackedWidget(ventanaPrincipal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ventanas.sizePolicy().hasHeightForWidth())
        self.ventanas.setSizePolicy(sizePolicy)
        self.ventanas.setMinimumSize(QtCore.QSize(1184, 700))
        self.ventanas.setMaximumSize(QtCore.QSize(1184, 700))
        self.ventanas.setObjectName("ventanas")
        self.paginaIniciarSesion = QtWidgets.QWidget()
        self.paginaIniciarSesion.setStyleSheet("")
        self.paginaIniciarSesion.setObjectName("paginaIniciarSesion")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.paginaIniciarSesion)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameGeneralIniciarSesion = QtWidgets.QFrame(self.paginaIniciarSesion)
        self.frameGeneralIniciarSesion.setMinimumSize(QtCore.QSize(922, 400))
        self.frameGeneralIniciarSesion.setMaximumSize(QtCore.QSize(922, 865))
        self.frameGeneralIniciarSesion.setStyleSheet("")
        self.frameGeneralIniciarSesion.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGeneralIniciarSesion.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGeneralIniciarSesion.setObjectName("frameGeneralIniciarSesion")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameGeneralIniciarSesion)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameInicioSesion = QtWidgets.QFrame(self.frameGeneralIniciarSesion)
        self.frameInicioSesion.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameInicioSesion.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameInicioSesion.setObjectName("frameInicioSesion")
        self.frameCamposInicioSesion = QtWidgets.QFrame(self.frameInicioSesion)
        self.frameCamposInicioSesion.setGeometry(QtCore.QRect(30, 90, 371, 441))
        self.frameCamposInicioSesion.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameCamposInicioSesion.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCamposInicioSesion.setObjectName("frameCamposInicioSesion")
        self.botonAcceder = QtWidgets.QPushButton(self.frameCamposInicioSesion)
        self.botonAcceder.setEnabled(True)
        self.botonAcceder.setGeometry(QtCore.QRect(120, 390, 120, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonAcceder.sizePolicy().hasHeightForWidth())
        self.botonAcceder.setSizePolicy(sizePolicy)
        self.botonAcceder.setMinimumSize(QtCore.QSize(120, 30))
        self.botonAcceder.setMaximumSize(QtCore.QSize(120, 30))
        self.botonAcceder.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonAcceder.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonAcceder.setStyleSheet("")
        self.botonAcceder.setObjectName("botonAcceder")
        self.layoutWidget = QtWidgets.QWidget(self.frameCamposInicioSesion)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 10, 261, 351))
        self.layoutWidget.setObjectName("layoutWidget")
        self.vlCamposIniciarSesion = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.vlCamposIniciarSesion.setContentsMargins(0, 0, 0, 0)
        self.vlCamposIniciarSesion.setSpacing(24)
        self.vlCamposIniciarSesion.setObjectName("vlCamposIniciarSesion")
        self.labelTituloIniciarSesion = QtWidgets.QLabel(self.layoutWidget)
        self.labelTituloIniciarSesion.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTituloIniciarSesion.setObjectName("labelTituloIniciarSesion")
        self.vlCamposIniciarSesion.addWidget(self.labelTituloIniciarSesion)
        self.vlCampoNombreUsuario = QtWidgets.QVBoxLayout()
        self.vlCampoNombreUsuario.setObjectName("vlCampoNombreUsuario")
        self.labelNombreUsuario = QtWidgets.QLabel(self.layoutWidget)
        self.labelNombreUsuario.setObjectName("labelNombreUsuario")
        self.vlCampoNombreUsuario.addWidget(self.labelNombreUsuario)
        self.inputNombreUsuario = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputNombreUsuario.setMinimumSize(QtCore.QSize(257, 32))
        self.inputNombreUsuario.setMaximumSize(QtCore.QSize(16777215, 32))
        self.inputNombreUsuario.setStyleSheet("background-image: url(:/iconos/iconos/user.png);\n"
"background-position: left;\n"
"background-repeat: no-repeat;")
        self.inputNombreUsuario.setAlignment(QtCore.Qt.AlignCenter)
        self.inputNombreUsuario.setObjectName("inputNombreUsuario")
        self.vlCampoNombreUsuario.addWidget(self.inputNombreUsuario)
        self.vlCamposIniciarSesion.addLayout(self.vlCampoNombreUsuario)
        self.vlCampoClave = QtWidgets.QVBoxLayout()
        self.vlCampoClave.setObjectName("vlCampoClave")
        self.labelClaveUsuario = QtWidgets.QLabel(self.layoutWidget)
        self.labelClaveUsuario.setObjectName("labelClaveUsuario")
        self.vlCampoClave.addWidget(self.labelClaveUsuario)
        self.inputClaveUsuario = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputClaveUsuario.setMinimumSize(QtCore.QSize(257, 32))
        self.inputClaveUsuario.setMaximumSize(QtCore.QSize(16777215, 32))
        self.inputClaveUsuario.setStyleSheet("background-image: url(:/iconos/iconos/padlock.png);\n"
"background-position: left;\n"
"background-repeat: no-repeat;\n"
"")
        self.inputClaveUsuario.setAlignment(QtCore.Qt.AlignCenter)
        self.inputClaveUsuario.setObjectName("inputClaveUsuario")
        self.vlCampoClave.addWidget(self.inputClaveUsuario)
        self.vlCamposIniciarSesion.addLayout(self.vlCampoClave)
        self.horizontalLayout.addWidget(self.frameInicioSesion)
        self.frameLogoDepartamento = QtWidgets.QFrame(self.frameGeneralIniciarSesion)
        self.frameLogoDepartamento.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLogoDepartamento.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLogoDepartamento.setObjectName("frameLogoDepartamento")
        self.labelImgLogo = QtWidgets.QLabel(self.frameLogoDepartamento)
        self.labelImgLogo.setGeometry(QtCore.QRect(0, 100, 441, 401))
        self.labelImgLogo.setText("")
        self.labelImgLogo.setPixmap(QtGui.QPixmap(":/logos/logos/logo_dgtic.png"))
        self.labelImgLogo.setScaledContents(True)
        self.labelImgLogo.setObjectName("labelImgLogo")
        self.horizontalLayout.addWidget(self.frameLogoDepartamento)
        self.verticalLayout.addWidget(self.frameGeneralIniciarSesion, 0, QtCore.Qt.AlignHCenter)
        self.ventanas.addWidget(self.paginaIniciarSesion)
        self.paginaApp = QtWidgets.QWidget()
        self.paginaApp.setStyleSheet("")
        self.paginaApp.setObjectName("paginaApp")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.paginaApp)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frameApp = QtWidgets.QFrame(self.paginaApp)
        self.frameApp.setMinimumSize(QtCore.QSize(1162, 685))
        self.frameApp.setMaximumSize(QtCore.QSize(1162, 685))
        self.frameApp.setStyleSheet("")
        self.frameApp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameApp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameApp.setObjectName("frameApp")
        self.frameInferior = QtWidgets.QFrame(self.frameApp)
        self.frameInferior.setGeometry(QtCore.QRect(10, 590, 1150, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameInferior.sizePolicy().hasHeightForWidth())
        self.frameInferior.setSizePolicy(sizePolicy)
        self.frameInferior.setMinimumSize(QtCore.QSize(1150, 0))
        self.frameInferior.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frameInferior.setStyleSheet("")
        self.frameInferior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameInferior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameInferior.setObjectName("frameInferior")
        self.layoutWidget1 = QtWidgets.QWidget(self.frameInferior)
        self.layoutWidget1.setGeometry(QtCore.QRect(140, 20, 880, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.hlBotonesInferiores = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.hlBotonesInferiores.setContentsMargins(0, 0, 0, 0)
        self.hlBotonesInferiores.setObjectName("hlBotonesInferiores")
        self.botonCrearUsuario = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonCrearUsuario.sizePolicy().hasHeightForWidth())
        self.botonCrearUsuario.setSizePolicy(sizePolicy)
        self.botonCrearUsuario.setMinimumSize(QtCore.QSize(170, 0))
        self.botonCrearUsuario.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonCrearUsuario.setStyleSheet("")
        self.botonCrearUsuario.setObjectName("botonCrearUsuario")
        self.hlBotonesInferiores.addWidget(self.botonCrearUsuario)
        self.botonCrearRespaldo = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonCrearRespaldo.sizePolicy().hasHeightForWidth())
        self.botonCrearRespaldo.setSizePolicy(sizePolicy)
        self.botonCrearRespaldo.setMinimumSize(QtCore.QSize(170, 0))
        self.botonCrearRespaldo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonCrearRespaldo.setObjectName("botonCrearRespaldo")
        self.hlBotonesInferiores.addWidget(self.botonCrearRespaldo)
        self.botonImportarRespaldo = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonImportarRespaldo.sizePolicy().hasHeightForWidth())
        self.botonImportarRespaldo.setSizePolicy(sizePolicy)
        self.botonImportarRespaldo.setMinimumSize(QtCore.QSize(170, 0))
        self.botonImportarRespaldo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonImportarRespaldo.setObjectName("botonImportarRespaldo")
        self.hlBotonesInferiores.addWidget(self.botonImportarRespaldo)
        self.botonGenerarReporte = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonGenerarReporte.sizePolicy().hasHeightForWidth())
        self.botonGenerarReporte.setSizePolicy(sizePolicy)
        self.botonGenerarReporte.setMinimumSize(QtCore.QSize(170, 0))
        self.botonGenerarReporte.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonGenerarReporte.setObjectName("botonGenerarReporte")
        self.hlBotonesInferiores.addWidget(self.botonGenerarReporte)
        self.botonCerrarSesion = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonCerrarSesion.sizePolicy().hasHeightForWidth())
        self.botonCerrarSesion.setSizePolicy(sizePolicy)
        self.botonCerrarSesion.setMinimumSize(QtCore.QSize(170, 0))
        self.botonCerrarSesion.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonCerrarSesion.setObjectName("botonCerrarSesion")
        self.hlBotonesInferiores.addWidget(self.botonCerrarSesion)
        self.frameSuperior = QtWidgets.QFrame(self.frameApp)
        self.frameSuperior.setGeometry(QtCore.QRect(12, 12, 1150, 237))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameSuperior.sizePolicy().hasHeightForWidth())
        self.frameSuperior.setSizePolicy(sizePolicy)
        self.frameSuperior.setMinimumSize(QtCore.QSize(1150, 0))
        self.frameSuperior.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frameSuperior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSuperior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSuperior.setObjectName("frameSuperior")
        self.lineaSeparadoraSeccionApp = QtWidgets.QFrame(self.frameSuperior)
        self.lineaSeparadoraSeccionApp.setGeometry(QtCore.QRect(0, 130, 1141, 20))
        self.lineaSeparadoraSeccionApp.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineaSeparadoraSeccionApp.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineaSeparadoraSeccionApp.setObjectName("lineaSeparadoraSeccionApp")
        self.layoutWidget2 = QtWidgets.QWidget(self.frameSuperior)
        self.layoutWidget2.setGeometry(QtCore.QRect(40, 0, 1081, 125))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.hlCamposRegistrarServicio = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.hlCamposRegistrarServicio.setContentsMargins(0, 0, 0, 0)
        self.hlCamposRegistrarServicio.setObjectName("hlCamposRegistrarServicio")
        self.vlRegistrarDepYFalla = QtWidgets.QVBoxLayout()
        self.vlRegistrarDepYFalla.setObjectName("vlRegistrarDepYFalla")
        self.glCampoRegistrarNombreDep = QtWidgets.QGridLayout()
        self.glCampoRegistrarNombreDep.setObjectName("glCampoRegistrarNombreDep")
        self.labelDepartamento = QtWidgets.QLabel(self.layoutWidget2)
        self.labelDepartamento.setObjectName("labelDepartamento")
        self.glCampoRegistrarNombreDep.addWidget(self.labelDepartamento, 0, 0, 1, 1)
        self.tbOtroDepartamento = QtWidgets.QToolButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbOtroDepartamento.sizePolicy().hasHeightForWidth())
        self.tbOtroDepartamento.setSizePolicy(sizePolicy)
        self.tbOtroDepartamento.setMinimumSize(QtCore.QSize(22, 27))
        self.tbOtroDepartamento.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tbOtroDepartamento.setObjectName("tbOtroDepartamento")
        self.glCampoRegistrarNombreDep.addWidget(self.tbOtroDepartamento, 1, 1, 1, 1)
        self.inputDepartamento = QtWidgets.QLineEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputDepartamento.sizePolicy().hasHeightForWidth())
        self.inputDepartamento.setSizePolicy(sizePolicy)
        self.inputDepartamento.setMinimumSize(QtCore.QSize(280, 27))
        self.inputDepartamento.setMaximumSize(QtCore.QSize(280, 16777215))
        self.inputDepartamento.setInputMethodHints(QtCore.Qt.ImhNone)
        self.inputDepartamento.setClearButtonEnabled(False)
        self.inputDepartamento.setObjectName("inputDepartamento")
        self.glCampoRegistrarNombreDep.addWidget(self.inputDepartamento, 1, 0, 1, 1)
        self.vlRegistrarDepYFalla.addLayout(self.glCampoRegistrarNombreDep)
        self.vlCampoRegistrarFallaPresenta = QtWidgets.QVBoxLayout()
        self.vlCampoRegistrarFallaPresenta.setObjectName("vlCampoRegistrarFallaPresenta")
        self.labelFallaPresenta = QtWidgets.QLabel(self.layoutWidget2)
        self.labelFallaPresenta.setObjectName("labelFallaPresenta")
        self.vlCampoRegistrarFallaPresenta.addWidget(self.labelFallaPresenta)
        self.inputFallaPresenta = QtWidgets.QLineEdit(self.layoutWidget2)
        self.inputFallaPresenta.setObjectName("inputFallaPresenta")
        self.vlCampoRegistrarFallaPresenta.addWidget(self.inputFallaPresenta)
        self.vlRegistrarDepYFalla.addLayout(self.vlCampoRegistrarFallaPresenta)
        self.hlCamposRegistrarServicio.addLayout(self.vlRegistrarDepYFalla)
        self.glCampoRegistrarTecnicosYServicio = QtWidgets.QGridLayout()
        self.glCampoRegistrarTecnicosYServicio.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.glCampoRegistrarTecnicosYServicio.setContentsMargins(-1, -1, 0, -1)
        self.glCampoRegistrarTecnicosYServicio.setObjectName("glCampoRegistrarTecnicosYServicio")
        self.labelNombreTecnico = QtWidgets.QLabel(self.layoutWidget2)
        self.labelNombreTecnico.setObjectName("labelNombreTecnico")
        self.glCampoRegistrarTecnicosYServicio.addWidget(self.labelNombreTecnico, 0, 0, 1, 1)
        self.labelServicioPrestado = QtWidgets.QLabel(self.layoutWidget2)
        self.labelServicioPrestado.setObjectName("labelServicioPrestado")
        self.glCampoRegistrarTecnicosYServicio.addWidget(self.labelServicioPrestado, 2, 0, 1, 1)
        self.inputServicioPrestado = QtWidgets.QLineEdit(self.layoutWidget2)
        self.inputServicioPrestado.setObjectName("inputServicioPrestado")
        self.glCampoRegistrarTecnicosYServicio.addWidget(self.inputServicioPrestado, 3, 0, 1, 1)
        self.tbOtroServicioPrestado = QtWidgets.QToolButton(self.layoutWidget2)
        self.tbOtroServicioPrestado.setMinimumSize(QtCore.QSize(27, 0))
        self.tbOtroServicioPrestado.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tbOtroServicioPrestado.setObjectName("tbOtroServicioPrestado")
        self.glCampoRegistrarTecnicosYServicio.addWidget(self.tbOtroServicioPrestado, 3, 1, 1, 1)
        self.inputNombreTecnico = QtWidgets.QLineEdit(self.layoutWidget2)
        self.inputNombreTecnico.setObjectName("inputNombreTecnico")
        self.glCampoRegistrarTecnicosYServicio.addWidget(self.inputNombreTecnico, 1, 0, 1, 2)
        self.hlCamposRegistrarServicio.addLayout(self.glCampoRegistrarTecnicosYServicio)
        self.vlObservacionesAdicionales = QtWidgets.QVBoxLayout()
        self.vlObservacionesAdicionales.setObjectName("vlObservacionesAdicionales")
        self.labelObservacionesAdicionales = QtWidgets.QLabel(self.layoutWidget2)
        self.labelObservacionesAdicionales.setObjectName("labelObservacionesAdicionales")
        self.vlObservacionesAdicionales.addWidget(self.labelObservacionesAdicionales)
        self.teObservacionesAdicionales = QtWidgets.QTextEdit(self.layoutWidget2)
        self.teObservacionesAdicionales.setObjectName("teObservacionesAdicionales")
        self.vlObservacionesAdicionales.addWidget(self.teObservacionesAdicionales)
        self.hlCamposRegistrarServicio.addLayout(self.vlObservacionesAdicionales)
        self.vlFechaYBotonRegistrarServicio = QtWidgets.QVBoxLayout()
        self.vlFechaYBotonRegistrarServicio.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.vlFechaYBotonRegistrarServicio.setContentsMargins(-1, 0, -1, 0)
        self.vlFechaYBotonRegistrarServicio.setSpacing(0)
        self.vlFechaYBotonRegistrarServicio.setObjectName("vlFechaYBotonRegistrarServicio")
        self.labelFecha = QtWidgets.QLabel(self.layoutWidget2)
        self.labelFecha.setMaximumSize(QtCore.QSize(16777215, 39))
        self.labelFecha.setObjectName("labelFecha")
        self.vlFechaYBotonRegistrarServicio.addWidget(self.labelFecha)
        self.deFecha = QtWidgets.QDateEdit(self.layoutWidget2)
        self.deFecha.setCalendarPopup(True)
        self.deFecha.setObjectName("deFecha")
        self.vlFechaYBotonRegistrarServicio.addWidget(self.deFecha)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.vlFechaYBotonRegistrarServicio.addItem(spacerItem)
        self.botonRegistrar = QtWidgets.QPushButton(self.layoutWidget2)
        self.botonRegistrar.setMinimumSize(QtCore.QSize(0, 30))
        self.botonRegistrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonRegistrar.setObjectName("botonRegistrar")
        self.vlFechaYBotonRegistrarServicio.addWidget(self.botonRegistrar)
        self.hlCamposRegistrarServicio.addLayout(self.vlFechaYBotonRegistrarServicio)
        self.hlCamposRegistrarServicio.setStretch(0, 2)
        self.hlCamposRegistrarServicio.setStretch(1, 3)
        self.hlCamposRegistrarServicio.setStretch(2, 3)
        self.hlCamposRegistrarServicio.setStretch(3, 3)
        self.layoutWidget3 = QtWidgets.QWidget(self.frameSuperior)
        self.layoutWidget3.setGeometry(QtCore.QRect(180, 140, 821, 62))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.vlSeccionFiltrarServicios = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.vlSeccionFiltrarServicios.setContentsMargins(0, 0, 0, 0)
        self.vlSeccionFiltrarServicios.setObjectName("vlSeccionFiltrarServicios")
        self.hlLabelsFiltroServicios = QtWidgets.QHBoxLayout()
        self.hlLabelsFiltroServicios.setContentsMargins(-1, -1, 145, -1)
        self.hlLabelsFiltroServicios.setSpacing(7)
        self.hlLabelsFiltroServicios.setObjectName("hlLabelsFiltroServicios")
        self.labelFiltroFecha = QtWidgets.QLabel(self.layoutWidget3)
        self.labelFiltroFecha.setMaximumSize(QtCore.QSize(295, 16777215))
        self.labelFiltroFecha.setObjectName("labelFiltroFecha")
        self.hlLabelsFiltroServicios.addWidget(self.labelFiltroFecha)
        self.labelFiltroDepartamento = QtWidgets.QLabel(self.layoutWidget3)
        self.labelFiltroDepartamento.setObjectName("labelFiltroDepartamento")
        self.hlLabelsFiltroServicios.addWidget(self.labelFiltroDepartamento)
        self.labelFiltroServicioPrestado = QtWidgets.QLabel(self.layoutWidget3)
        self.labelFiltroServicioPrestado.setObjectName("labelFiltroServicioPrestado")
        self.hlLabelsFiltroServicios.addWidget(self.labelFiltroServicioPrestado)
        self.vlSeccionFiltrarServicios.addLayout(self.hlLabelsFiltroServicios)
        self.hlElementosFiltroServicio = QtWidgets.QHBoxLayout()
        self.hlElementosFiltroServicio.setObjectName("hlElementosFiltroServicio")
        self.deFiltroFecha = QtWidgets.QDateEdit(self.layoutWidget3)
        self.deFiltroFecha.setMaximumSize(QtCore.QSize(295, 16777215))
        self.deFiltroFecha.setReadOnly(False)
        self.deFiltroFecha.setKeyboardTracking(True)
        self.deFiltroFecha.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.deFiltroFecha.setCalendarPopup(True)
        self.deFiltroFecha.setTimeSpec(QtCore.Qt.LocalTime)
        self.deFiltroFecha.setObjectName("deFiltroFecha")
        self.hlElementosFiltroServicio.addWidget(self.deFiltroFecha)
        self.inputFiltroDepartamento = QtWidgets.QLineEdit(self.layoutWidget3)
        self.inputFiltroDepartamento.setObjectName("inputFiltroDepartamento")
        self.hlElementosFiltroServicio.addWidget(self.inputFiltroDepartamento)
        self.inputFiltroServicioPrestado = QtWidgets.QLineEdit(self.layoutWidget3)
        self.inputFiltroServicioPrestado.setObjectName("inputFiltroServicioPrestado")
        self.hlElementosFiltroServicio.addWidget(self.inputFiltroServicioPrestado)
        self.botonBuscarServicios = QtWidgets.QPushButton(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonBuscarServicios.sizePolicy().hasHeightForWidth())
        self.botonBuscarServicios.setSizePolicy(sizePolicy)
        self.botonBuscarServicios.setMinimumSize(QtCore.QSize(140, 27))
        self.botonBuscarServicios.setMaximumSize(QtCore.QSize(140, 26))
        self.botonBuscarServicios.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonBuscarServicios.setObjectName("botonBuscarServicios")
        self.hlElementosFiltroServicio.addWidget(self.botonBuscarServicios)
        self.hlElementosFiltroServicio.setStretch(0, 1)
        self.hlElementosFiltroServicio.setStretch(1, 1)
        self.hlElementosFiltroServicio.setStretch(2, 1)
        self.vlSeccionFiltrarServicios.addLayout(self.hlElementosFiltroServicio)
        self.botonRefrescarApp = QtWidgets.QPushButton(self.frameSuperior)
        self.botonRefrescarApp.setGeometry(QtCore.QRect(0, 0, 31, 28))
        self.botonRefrescarApp.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonRefrescarApp.setStyleSheet("")
        self.botonRefrescarApp.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/iconos/iconos/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonRefrescarApp.setIcon(icon1)
        self.botonRefrescarApp.setObjectName("botonRefrescarApp")
        self.labelErrorFiltro = QtWidgets.QLabel(self.frameSuperior)
        self.labelErrorFiltro.setGeometry(QtCore.QRect(180, 200, 821, 31))
        self.labelErrorFiltro.setText("")
        self.labelErrorFiltro.setAlignment(QtCore.Qt.AlignCenter)
        self.labelErrorFiltro.setObjectName("labelErrorFiltro")
        self.frameRegistros = QtWidgets.QFrame(self.frameApp)
        self.frameRegistros.setGeometry(QtCore.QRect(12, 256, 1131, 341))
        self.frameRegistros.setMinimumSize(QtCore.QSize(0, 300))
        self.frameRegistros.setMaximumSize(QtCore.QSize(1150, 450))
        self.frameRegistros.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRegistros.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRegistros.setObjectName("frameRegistros")
        self.tvRegistros = QtWidgets.QTableView(self.frameRegistros)
        self.tvRegistros.setGeometry(QtCore.QRect(10, 10, 1111, 321))
        self.tvRegistros.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tvRegistros.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tvRegistros.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tvRegistros.setShowGrid(True)
        self.tvRegistros.setGridStyle(QtCore.Qt.SolidLine)
        self.tvRegistros.setCornerButtonEnabled(True)
        self.tvRegistros.setObjectName("tvRegistros")
        self.tvRegistros.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.frameApp, 0, QtCore.Qt.AlignHCenter)
        self.ventanas.addWidget(self.paginaApp)
        self.paginaCrearUsuario = QtWidgets.QWidget()
        self.paginaCrearUsuario.setObjectName("paginaCrearUsuario")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.paginaCrearUsuario)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frameGeneralUsuarios = QtWidgets.QFrame(self.paginaCrearUsuario)
        self.frameGeneralUsuarios.setMinimumSize(QtCore.QSize(1164, 685))
        self.frameGeneralUsuarios.setMaximumSize(QtCore.QSize(1184, 685))
        self.frameGeneralUsuarios.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGeneralUsuarios.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGeneralUsuarios.setObjectName("frameGeneralUsuarios")
        self.frameSeccionRegistrarUsuario = QtWidgets.QFrame(self.frameGeneralUsuarios)
        self.frameSeccionRegistrarUsuario.setGeometry(QtCore.QRect(9, 10, 1161, 209))
        self.frameSeccionRegistrarUsuario.setMinimumSize(QtCore.QSize(876, 0))
        self.frameSeccionRegistrarUsuario.setMaximumSize(QtCore.QSize(16777215, 209))
        self.frameSeccionRegistrarUsuario.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSeccionRegistrarUsuario.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSeccionRegistrarUsuario.setObjectName("frameSeccionRegistrarUsuario")
        self.botonRegistrarUsuario = QtWidgets.QPushButton(self.frameSeccionRegistrarUsuario)
        self.botonRegistrarUsuario.setGeometry(QtCore.QRect(830, 120, 141, 31))
        self.botonRegistrarUsuario.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonRegistrarUsuario.setObjectName("botonRegistrarUsuario")
        self.labelTituloRegistrarUsuario = QtWidgets.QLabel(self.frameSeccionRegistrarUsuario)
        self.labelTituloRegistrarUsuario.setGeometry(QtCore.QRect(494, 10, 231, 20))
        self.labelTituloRegistrarUsuario.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTituloRegistrarUsuario.setObjectName("labelTituloRegistrarUsuario")
        self.layoutWidget4 = QtWidgets.QWidget(self.frameSeccionRegistrarUsuario)
        self.layoutWidget4.setGeometry(QtCore.QRect(430, 60, 341, 97))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.glCamposRegistrarUsuario = QtWidgets.QGridLayout(self.layoutWidget4)
        self.glCamposRegistrarUsuario.setContentsMargins(0, 0, 0, 0)
        self.glCamposRegistrarUsuario.setObjectName("glCamposRegistrarUsuario")
        self.labelRegistrarNombreUsuario = QtWidgets.QLabel(self.layoutWidget4)
        self.labelRegistrarNombreUsuario.setObjectName("labelRegistrarNombreUsuario")
        self.glCamposRegistrarUsuario.addWidget(self.labelRegistrarNombreUsuario, 0, 0, 1, 1)
        self.inputRegistrarNombreUsuario = QtWidgets.QLineEdit(self.layoutWidget4)
        self.inputRegistrarNombreUsuario.setObjectName("inputRegistrarNombreUsuario")
        self.glCamposRegistrarUsuario.addWidget(self.inputRegistrarNombreUsuario, 0, 1, 1, 1)
        self.labelRegistrarRol = QtWidgets.QLabel(self.layoutWidget4)
        self.labelRegistrarRol.setObjectName("labelRegistrarRol")
        self.glCamposRegistrarUsuario.addWidget(self.labelRegistrarRol, 1, 0, 1, 1)
        self.labelRegistrarClave = QtWidgets.QLabel(self.layoutWidget4)
        self.labelRegistrarClave.setObjectName("labelRegistrarClave")
        self.glCamposRegistrarUsuario.addWidget(self.labelRegistrarClave, 2, 0, 1, 1)
        self.inputRegistrarClaveUsuario = QtWidgets.QLineEdit(self.layoutWidget4)
        self.inputRegistrarClaveUsuario.setObjectName("inputRegistrarClaveUsuario")
        self.glCamposRegistrarUsuario.addWidget(self.inputRegistrarClaveUsuario, 2, 1, 1, 1)
        self.cbRolesRegistrarUsuario = QtWidgets.QComboBox(self.layoutWidget4)
        self.cbRolesRegistrarUsuario.setObjectName("cbRolesRegistrarUsuario")
        self.cbRolesRegistrarUsuario.addItem("")
        self.cbRolesRegistrarUsuario.addItem("")
        self.glCamposRegistrarUsuario.addWidget(self.cbRolesRegistrarUsuario, 1, 1, 1, 1)
        self.botonRefrescarUsuarios = QtWidgets.QPushButton(self.frameSeccionRegistrarUsuario)
        self.botonRefrescarUsuarios.setGeometry(QtCore.QRect(0, 0, 31, 28))
        self.botonRefrescarUsuarios.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonRefrescarUsuarios.setStyleSheet("")
        self.botonRefrescarUsuarios.setText("")
        self.botonRefrescarUsuarios.setIcon(icon1)
        self.botonRefrescarUsuarios.setObjectName("botonRefrescarUsuarios")
        self.lineaSeparadoraSeccionUsuarios = QtWidgets.QFrame(self.frameSeccionRegistrarUsuario)
        self.lineaSeparadoraSeccionUsuarios.setGeometry(QtCore.QRect(0, 170, 1151, 21))
        self.lineaSeparadoraSeccionUsuarios.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineaSeparadoraSeccionUsuarios.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineaSeparadoraSeccionUsuarios.setObjectName("lineaSeparadoraSeccionUsuarios")
        self.frameInferiorSeccionUsuarios = QtWidgets.QFrame(self.frameGeneralUsuarios)
        self.frameInferiorSeccionUsuarios.setGeometry(QtCore.QRect(10, 620, 1160, 61))
        self.frameInferiorSeccionUsuarios.setMinimumSize(QtCore.QSize(876, 0))
        self.frameInferiorSeccionUsuarios.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frameInferiorSeccionUsuarios.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameInferiorSeccionUsuarios.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameInferiorSeccionUsuarios.setObjectName("frameInferiorSeccionUsuarios")
        self.botonRegresarSeccionUsuarios = QtWidgets.QPushButton(self.frameInferiorSeccionUsuarios)
        self.botonRegresarSeccionUsuarios.setGeometry(QtCore.QRect(500, 10, 191, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonRegresarSeccionUsuarios.sizePolicy().hasHeightForWidth())
        self.botonRegresarSeccionUsuarios.setSizePolicy(sizePolicy)
        self.botonRegresarSeccionUsuarios.setMaximumSize(QtCore.QSize(200, 35))
        self.botonRegresarSeccionUsuarios.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonRegresarSeccionUsuarios.setObjectName("botonRegresarSeccionUsuarios")
        self.frameListaUsuarios = QtWidgets.QFrame(self.frameGeneralUsuarios)
        self.frameListaUsuarios.setGeometry(QtCore.QRect(12, 223, 1141, 391))
        self.frameListaUsuarios.setMinimumSize(QtCore.QSize(852, 0))
        self.frameListaUsuarios.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameListaUsuarios.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameListaUsuarios.setObjectName("frameListaUsuarios")
        self.tvUsuarios = QtWidgets.QTableView(self.frameListaUsuarios)
        self.tvUsuarios.setGeometry(QtCore.QRect(170, 0, 852, 381))
        self.tvUsuarios.setMaximumSize(QtCore.QSize(852, 16777215))
        self.tvUsuarios.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tvUsuarios.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tvUsuarios.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tvUsuarios.setObjectName("tvUsuarios")
        self.tvUsuarios.verticalHeader().setVisible(False)
        self.verticalLayout_8.addWidget(self.frameGeneralUsuarios, 0, QtCore.Qt.AlignHCenter)
        self.ventanas.addWidget(self.paginaCrearUsuario)
        self.paginaDepartamentos = QtWidgets.QWidget()
        self.paginaDepartamentos.setObjectName("paginaDepartamentos")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.paginaDepartamentos)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frameGeneralDepartamentos = QtWidgets.QFrame(self.paginaDepartamentos)
        self.frameGeneralDepartamentos.setMinimumSize(QtCore.QSize(1165, 685))
        self.frameGeneralDepartamentos.setMaximumSize(QtCore.QSize(1184, 685))
        self.frameGeneralDepartamentos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGeneralDepartamentos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGeneralDepartamentos.setObjectName("frameGeneralDepartamentos")
        self.frameSeccionRegistrarDepartamento = QtWidgets.QFrame(self.frameGeneralDepartamentos)
        self.frameSeccionRegistrarDepartamento.setGeometry(QtCore.QRect(9, 12, 1151, 229))
        self.frameSeccionRegistrarDepartamento.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSeccionRegistrarDepartamento.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSeccionRegistrarDepartamento.setObjectName("frameSeccionRegistrarDepartamento")
        self.labelTituloRegistrarDepartamento = QtWidgets.QLabel(self.frameSeccionRegistrarDepartamento)
        self.labelTituloRegistrarDepartamento.setGeometry(QtCore.QRect(290, 10, 631, 31))
        self.labelTituloRegistrarDepartamento.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTituloRegistrarDepartamento.setObjectName("labelTituloRegistrarDepartamento")
        self.lineaSeparadoraSeccionDepartamento = QtWidgets.QFrame(self.frameSeccionRegistrarDepartamento)
        self.lineaSeparadoraSeccionDepartamento.setGeometry(QtCore.QRect(0, 140, 1151, 21))
        self.lineaSeparadoraSeccionDepartamento.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineaSeparadoraSeccionDepartamento.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineaSeparadoraSeccionDepartamento.setObjectName("lineaSeparadoraSeccionDepartamento")
        self.layoutWidget5 = QtWidgets.QWidget(self.frameSeccionRegistrarDepartamento)
        self.layoutWidget5.setGeometry(QtCore.QRect(296, 170, 601, 32))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.hlSeccionBuscarDepartamento = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.hlSeccionBuscarDepartamento.setContentsMargins(0, 0, 0, 0)
        self.hlSeccionBuscarDepartamento.setSpacing(7)
        self.hlSeccionBuscarDepartamento.setObjectName("hlSeccionBuscarDepartamento")
        self.hlBuscarDepartamento = QtWidgets.QHBoxLayout()
        self.hlBuscarDepartamento.setSpacing(6)
        self.hlBuscarDepartamento.setObjectName("hlBuscarDepartamento")
        self.labelBuscarDepartamento = QtWidgets.QLabel(self.layoutWidget5)
        self.labelBuscarDepartamento.setObjectName("labelBuscarDepartamento")
        self.hlBuscarDepartamento.addWidget(self.labelBuscarDepartamento)
        self.inputBuscarDepartamento = QtWidgets.QLineEdit(self.layoutWidget5)
        self.inputBuscarDepartamento.setObjectName("inputBuscarDepartamento")
        self.hlBuscarDepartamento.addWidget(self.inputBuscarDepartamento)
        self.hlSeccionBuscarDepartamento.addLayout(self.hlBuscarDepartamento)
        self.botonBuscarDepartamento = QtWidgets.QPushButton(self.layoutWidget5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonBuscarDepartamento.sizePolicy().hasHeightForWidth())
        self.botonBuscarDepartamento.setSizePolicy(sizePolicy)
        self.botonBuscarDepartamento.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonBuscarDepartamento.setObjectName("botonBuscarDepartamento")
        self.hlSeccionBuscarDepartamento.addWidget(self.botonBuscarDepartamento)
        self.hlSeccionBuscarDepartamento.setStretch(0, 3)
        self.hlSeccionBuscarDepartamento.setStretch(1, 1)
        self.layoutWidget6 = QtWidgets.QWidget(self.frameSeccionRegistrarDepartamento)
        self.layoutWidget6.setGeometry(QtCore.QRect(290, 90, 631, 32))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.hlSeccionRegistrarDepartamento = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.hlSeccionRegistrarDepartamento.setContentsMargins(0, 0, 0, 0)
        self.hlSeccionRegistrarDepartamento.setObjectName("hlSeccionRegistrarDepartamento")
        self.hlCamposRegistrarDepartamento = QtWidgets.QHBoxLayout()
        self.hlCamposRegistrarDepartamento.setObjectName("hlCamposRegistrarDepartamento")
        self.labelNombreDepartamento = QtWidgets.QLabel(self.layoutWidget6)
        self.labelNombreDepartamento.setObjectName("labelNombreDepartamento")
        self.hlCamposRegistrarDepartamento.addWidget(self.labelNombreDepartamento)
        self.inputNombreDepartamento = QtWidgets.QLineEdit(self.layoutWidget6)
        self.inputNombreDepartamento.setObjectName("inputNombreDepartamento")
        self.hlCamposRegistrarDepartamento.addWidget(self.inputNombreDepartamento)
        self.hlSeccionRegistrarDepartamento.addLayout(self.hlCamposRegistrarDepartamento)
        self.botonRegistrarDepartamento = QtWidgets.QPushButton(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonRegistrarDepartamento.sizePolicy().hasHeightForWidth())
        self.botonRegistrarDepartamento.setSizePolicy(sizePolicy)
        self.botonRegistrarDepartamento.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonRegistrarDepartamento.setObjectName("botonRegistrarDepartamento")
        self.hlSeccionRegistrarDepartamento.addWidget(self.botonRegistrarDepartamento)
        self.hlSeccionRegistrarDepartamento.setStretch(0, 3)
        self.hlSeccionRegistrarDepartamento.setStretch(1, 1)
        self.labelFiltroSeccionDepartamento = QtWidgets.QLabel(self.frameSeccionRegistrarDepartamento)
        self.labelFiltroSeccionDepartamento.setGeometry(QtCore.QRect(300, 200, 591, 20))
        self.labelFiltroSeccionDepartamento.setText("")
        self.labelFiltroSeccionDepartamento.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFiltroSeccionDepartamento.setObjectName("labelFiltroSeccionDepartamento")
        self.botonRefrescarDepartamentos = QtWidgets.QPushButton(self.frameSeccionRegistrarDepartamento)
        self.botonRefrescarDepartamentos.setGeometry(QtCore.QRect(0, 0, 31, 28))
        self.botonRefrescarDepartamentos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonRefrescarDepartamentos.setStyleSheet("")
        self.botonRefrescarDepartamentos.setText("")
        self.botonRefrescarDepartamentos.setIcon(icon1)
        self.botonRefrescarDepartamentos.setObjectName("botonRefrescarDepartamentos")
        self.frameListaDepartamentos = QtWidgets.QFrame(self.frameGeneralDepartamentos)
        self.frameListaDepartamentos.setGeometry(QtCore.QRect(154, 248, 876, 371))
        self.frameListaDepartamentos.setMaximumSize(QtCore.QSize(876, 450))
        self.frameListaDepartamentos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameListaDepartamentos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameListaDepartamentos.setObjectName("frameListaDepartamentos")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frameListaDepartamentos)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tvDepartamentos = QtWidgets.QTableView(self.frameListaDepartamentos)
        self.tvDepartamentos.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tvDepartamentos.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tvDepartamentos.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tvDepartamentos.setObjectName("tvDepartamentos")
        self.tvDepartamentos.verticalHeader().setVisible(False)
        self.verticalLayout_7.addWidget(self.tvDepartamentos)
        self.frameInferiorSeccionDepartamentos = QtWidgets.QFrame(self.frameGeneralDepartamentos)
        self.frameInferiorSeccionDepartamentos.setGeometry(QtCore.QRect(160, 620, 876, 51))
        self.frameInferiorSeccionDepartamentos.setMinimumSize(QtCore.QSize(876, 0))
        self.frameInferiorSeccionDepartamentos.setMaximumSize(QtCore.QSize(876, 130))
        self.frameInferiorSeccionDepartamentos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameInferiorSeccionDepartamentos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameInferiorSeccionDepartamentos.setObjectName("frameInferiorSeccionDepartamentos")
        self.botonRegresarSeccionDepartamentos = QtWidgets.QPushButton(self.frameInferiorSeccionDepartamentos)
        self.botonRegresarSeccionDepartamentos.setGeometry(QtCore.QRect(340, 10, 200, 35))
        self.botonRegresarSeccionDepartamentos.setMinimumSize(QtCore.QSize(200, 35))
        self.botonRegresarSeccionDepartamentos.setMaximumSize(QtCore.QSize(200, 35))
        self.botonRegresarSeccionDepartamentos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonRegresarSeccionDepartamentos.setObjectName("botonRegresarSeccionDepartamentos")
        self.verticalLayout_6.addWidget(self.frameGeneralDepartamentos, 0, QtCore.Qt.AlignHCenter)
        self.ventanas.addWidget(self.paginaDepartamentos)
        self.paginaTiposServicio = QtWidgets.QWidget()
        self.paginaTiposServicio.setObjectName("paginaTiposServicio")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.paginaTiposServicio)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frameGeneralTipoServicio = QtWidgets.QFrame(self.paginaTiposServicio)
        self.frameGeneralTipoServicio.setMinimumSize(QtCore.QSize(1165, 685))
        self.frameGeneralTipoServicio.setMaximumSize(QtCore.QSize(1184, 685))
        self.frameGeneralTipoServicio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGeneralTipoServicio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGeneralTipoServicio.setObjectName("frameGeneralTipoServicio")
        self.frameSuperiorTipoServicio = QtWidgets.QFrame(self.frameGeneralTipoServicio)
        self.frameSuperiorTipoServicio.setGeometry(QtCore.QRect(9, 12, 1151, 229))
        self.frameSuperiorTipoServicio.setMinimumSize(QtCore.QSize(876, 0))
        self.frameSuperiorTipoServicio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSuperiorTipoServicio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSuperiorTipoServicio.setObjectName("frameSuperiorTipoServicio")
        self.labelTituloRegistrarTipoServicio = QtWidgets.QLabel(self.frameSuperiorTipoServicio)
        self.labelTituloRegistrarTipoServicio.setGeometry(QtCore.QRect(310, 10, 591, 41))
        self.labelTituloRegistrarTipoServicio.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTituloRegistrarTipoServicio.setObjectName("labelTituloRegistrarTipoServicio")
        self.lineaSeparadoraSeccionTipoServicio = QtWidgets.QFrame(self.frameSuperiorTipoServicio)
        self.lineaSeparadoraSeccionTipoServicio.setGeometry(QtCore.QRect(0, 130, 1151, 20))
        self.lineaSeparadoraSeccionTipoServicio.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineaSeparadoraSeccionTipoServicio.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineaSeparadoraSeccionTipoServicio.setObjectName("lineaSeparadoraSeccionTipoServicio")
        self.layoutWidget7 = QtWidgets.QWidget(self.frameSuperiorTipoServicio)
        self.layoutWidget7.setGeometry(QtCore.QRect(310, 80, 591, 32))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.hlRegistrarTipoServicio = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.hlRegistrarTipoServicio.setContentsMargins(0, 0, 0, 0)
        self.hlRegistrarTipoServicio.setObjectName("hlRegistrarTipoServicio")
        self.labelCampoTipoServicio = QtWidgets.QLabel(self.layoutWidget7)
        self.labelCampoTipoServicio.setObjectName("labelCampoTipoServicio")
        self.hlRegistrarTipoServicio.addWidget(self.labelCampoTipoServicio)
        self.inputRegistrarTipoServicio = QtWidgets.QLineEdit(self.layoutWidget7)
        self.inputRegistrarTipoServicio.setObjectName("inputRegistrarTipoServicio")
        self.hlRegistrarTipoServicio.addWidget(self.inputRegistrarTipoServicio)
        self.botonRegistrarTipoServicio = QtWidgets.QPushButton(self.layoutWidget7)
        self.botonRegistrarTipoServicio.setMinimumSize(QtCore.QSize(155, 30))
        self.botonRegistrarTipoServicio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonRegistrarTipoServicio.setObjectName("botonRegistrarTipoServicio")
        self.hlRegistrarTipoServicio.addWidget(self.botonRegistrarTipoServicio)
        self.layoutWidget8 = QtWidgets.QWidget(self.frameSuperiorTipoServicio)
        self.layoutWidget8.setGeometry(QtCore.QRect(330, 160, 551, 32))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.hlFiltrarTipoServicio = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.hlFiltrarTipoServicio.setContentsMargins(0, 0, 0, 0)
        self.hlFiltrarTipoServicio.setObjectName("hlFiltrarTipoServicio")
        self.labelFiltroTipoServicio = QtWidgets.QLabel(self.layoutWidget8)
        self.labelFiltroTipoServicio.setObjectName("labelFiltroTipoServicio")
        self.hlFiltrarTipoServicio.addWidget(self.labelFiltroTipoServicio)
        self.inputFiltroTipoServicio = QtWidgets.QLineEdit(self.layoutWidget8)
        self.inputFiltroTipoServicio.setObjectName("inputFiltroTipoServicio")
        self.hlFiltrarTipoServicio.addWidget(self.inputFiltroTipoServicio)
        self.botonBuscarTipoServicio = QtWidgets.QPushButton(self.layoutWidget8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonBuscarTipoServicio.sizePolicy().hasHeightForWidth())
        self.botonBuscarTipoServicio.setSizePolicy(sizePolicy)
        self.botonBuscarTipoServicio.setMinimumSize(QtCore.QSize(148, 30))
        self.botonBuscarTipoServicio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonBuscarTipoServicio.setObjectName("botonBuscarTipoServicio")
        self.hlFiltrarTipoServicio.addWidget(self.botonBuscarTipoServicio)
        self.labelFiltroSeccionTipoServicio = QtWidgets.QLabel(self.frameSuperiorTipoServicio)
        self.labelFiltroSeccionTipoServicio.setGeometry(QtCore.QRect(310, 200, 591, 20))
        self.labelFiltroSeccionTipoServicio.setText("")
        self.labelFiltroSeccionTipoServicio.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFiltroSeccionTipoServicio.setObjectName("labelFiltroSeccionTipoServicio")
        self.botonRefrescarTiposServicio = QtWidgets.QPushButton(self.frameSuperiorTipoServicio)
        self.botonRefrescarTiposServicio.setGeometry(QtCore.QRect(0, 0, 31, 28))
        self.botonRefrescarTiposServicio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonRefrescarTiposServicio.setStyleSheet("")
        self.botonRefrescarTiposServicio.setText("")
        self.botonRefrescarTiposServicio.setIcon(icon1)
        self.botonRefrescarTiposServicio.setObjectName("botonRefrescarTiposServicio")
        self.frameRegistrosTipoServicio = QtWidgets.QFrame(self.frameGeneralTipoServicio)
        self.frameRegistrosTipoServicio.setGeometry(QtCore.QRect(154, 248, 876, 361))
        self.frameRegistrosTipoServicio.setMaximumSize(QtCore.QSize(876, 450))
        self.frameRegistrosTipoServicio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRegistrosTipoServicio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRegistrosTipoServicio.setObjectName("frameRegistrosTipoServicio")
        self.tvRegistrosTipoServicio = QtWidgets.QTableView(self.frameRegistrosTipoServicio)
        self.tvRegistrosTipoServicio.setGeometry(QtCore.QRect(2, 12, 871, 341))
        self.tvRegistrosTipoServicio.setMaximumSize(QtCore.QSize(16777215, 430))
        self.tvRegistrosTipoServicio.setObjectName("tvRegistrosTipoServicio")
        self.tvRegistrosTipoServicio.verticalHeader().setVisible(False)
        self.frameInferiorTipoServicio = QtWidgets.QFrame(self.frameGeneralTipoServicio)
        self.frameInferiorTipoServicio.setGeometry(QtCore.QRect(150, 620, 876, 61))
        self.frameInferiorTipoServicio.setMaximumSize(QtCore.QSize(876, 130))
        self.frameInferiorTipoServicio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameInferiorTipoServicio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameInferiorTipoServicio.setObjectName("frameInferiorTipoServicio")
        self.botonRegresarSeccionTipoServicio = QtWidgets.QPushButton(self.frameInferiorTipoServicio)
        self.botonRegresarSeccionTipoServicio.setGeometry(QtCore.QRect(350, 10, 200, 35))
        self.botonRegresarSeccionTipoServicio.setMinimumSize(QtCore.QSize(200, 35))
        self.botonRegresarSeccionTipoServicio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonRegresarSeccionTipoServicio.setObjectName("botonRegresarSeccionTipoServicio")
        self.verticalLayout_9.addWidget(self.frameGeneralTipoServicio, 0, QtCore.Qt.AlignHCenter)
        self.ventanas.addWidget(self.paginaTiposServicio)
        self.verticalLayout_2.addWidget(self.ventanas, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)

        self.retranslateUi(ventanaPrincipal)
        self.ventanas.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ventanaPrincipal)

    def retranslateUi(self, ventanaPrincipal):
        _translate = QtCore.QCoreApplication.translate
        ventanaPrincipal.setWindowTitle(_translate("ventanaPrincipal", "Iniciar Sesión"))
        self.botonAcceder.setText(_translate("ventanaPrincipal", "Acceder"))
        self.labelTituloIniciarSesion.setText(_translate("ventanaPrincipal", "Iniciar Sesión"))
        self.labelNombreUsuario.setText(_translate("ventanaPrincipal", "Usuario"))
        self.inputNombreUsuario.setPlaceholderText(_translate("ventanaPrincipal", "Ingresa su usuario"))
        self.labelClaveUsuario.setText(_translate("ventanaPrincipal", "Contraseña"))
        self.inputClaveUsuario.setPlaceholderText(_translate("ventanaPrincipal", "Ingrese su contraseña"))
        self.botonCrearUsuario.setText(_translate("ventanaPrincipal", "Crear nuevo usuario"))
        self.botonCrearRespaldo.setText(_translate("ventanaPrincipal", "Crear respaldo"))
        self.botonImportarRespaldo.setText(_translate("ventanaPrincipal", "Importar respaldo"))
        self.botonGenerarReporte.setText(_translate("ventanaPrincipal", "Generar reporte"))
        self.botonCerrarSesion.setText(_translate("ventanaPrincipal", "Cerrar sesión"))
        self.labelDepartamento.setText(_translate("ventanaPrincipal", "Departamento:"))
        self.tbOtroDepartamento.setText(_translate("ventanaPrincipal", "..."))
        self.labelFallaPresenta.setText(_translate("ventanaPrincipal", "Falla que presenta:"))
        self.labelNombreTecnico.setText(_translate("ventanaPrincipal", "Nombre del técnico:"))
        self.labelServicioPrestado.setText(_translate("ventanaPrincipal", "Servicio prestado:"))
        self.tbOtroServicioPrestado.setText(_translate("ventanaPrincipal", "..."))
        self.labelObservacionesAdicionales.setText(_translate("ventanaPrincipal", "Observaciones adicionales:"))
        self.labelFecha.setText(_translate("ventanaPrincipal", "Fecha:"))
        self.botonRegistrar.setText(_translate("ventanaPrincipal", "Registrar"))
        self.labelFiltroFecha.setText(_translate("ventanaPrincipal", "Fecha"))
        self.labelFiltroDepartamento.setText(_translate("ventanaPrincipal", "Departamento"))
        self.labelFiltroServicioPrestado.setText(_translate("ventanaPrincipal", "Servicio prestado"))
        self.botonBuscarServicios.setText(_translate("ventanaPrincipal", "Buscar"))
        self.botonRegistrarUsuario.setText(_translate("ventanaPrincipal", "Registrar"))
        self.labelTituloRegistrarUsuario.setText(_translate("ventanaPrincipal", "Crear nuevo usuario"))
        self.labelRegistrarNombreUsuario.setText(_translate("ventanaPrincipal", "Nombre de usuario:"))
        self.labelRegistrarRol.setText(_translate("ventanaPrincipal", "Rol:"))
        self.labelRegistrarClave.setText(_translate("ventanaPrincipal", "Contraseña:"))
        self.cbRolesRegistrarUsuario.setItemText(0, _translate("ventanaPrincipal", "ADMINISTRADOR"))
        self.cbRolesRegistrarUsuario.setItemText(1, _translate("ventanaPrincipal", "ESTANDAR"))
        self.botonRegresarSeccionUsuarios.setText(_translate("ventanaPrincipal", "Regresar"))
        self.labelTituloRegistrarDepartamento.setText(_translate("ventanaPrincipal", "Crear nuevo departamento"))
        self.labelBuscarDepartamento.setText(_translate("ventanaPrincipal", "Departamento:"))
        self.botonBuscarDepartamento.setText(_translate("ventanaPrincipal", "Buscar"))
        self.labelNombreDepartamento.setText(_translate("ventanaPrincipal", "Nombre del departamento:"))
        self.botonRegistrarDepartamento.setText(_translate("ventanaPrincipal", "Registrar"))
        self.botonRegresarSeccionDepartamentos.setText(_translate("ventanaPrincipal", "Regresar"))
        self.labelTituloRegistrarTipoServicio.setText(_translate("ventanaPrincipal", "Crear nuevo tipo de servicio"))
        self.labelCampoTipoServicio.setText(_translate("ventanaPrincipal", "Nombre del tipo de servicio:"))
        self.botonRegistrarTipoServicio.setText(_translate("ventanaPrincipal", "Registrar"))
        self.labelFiltroTipoServicio.setText(_translate("ventanaPrincipal", "Tipo de servicio:"))
        self.botonBuscarTipoServicio.setText(_translate("ventanaPrincipal", "Buscar"))
        self.botonRegresarSeccionTipoServicio.setText(_translate("ventanaPrincipal", "Regresar"))
import qtRecursosIconos_rc
import qtRecursosLogos_rc
