# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\ventanas\ventanas_qt\VentanaInfoTipoServicio.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaInfoTipoServicio(object):
    def setupUi(self, VentanaInfoTipoServicio):
        VentanaInfoTipoServicio.setObjectName("VentanaInfoTipoServicio")
        VentanaInfoTipoServicio.resize(475, 268)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconos/iconos/icono-app-dgtic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        VentanaInfoTipoServicio.setWindowIcon(icon)
        VentanaInfoTipoServicio.setStyleSheet("#VentanaInfoTipoServicio {\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"#frameGeneralInfoTipoServicio .QPushButton{\n"
"    color: #ffffff;\n"
"    background-color: #417fd2;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    border-radius: 6px;\n"
"    padding-bottom: 2px;\n"
"    font: 8.5pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"#frameGeneralInfoTipoServicio .QPushButton::hover{\n"
"    background-color: #5c8bc9;\n"
"}\n"
"\n"
"#frameGeneralInfoTipoServicio .QPushButton::pressed{\n"
"    background-color: #063c85;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(VentanaInfoTipoServicio)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameGeneralInfoTipoServicio = QtWidgets.QFrame(VentanaInfoTipoServicio)
        self.frameGeneralInfoTipoServicio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGeneralInfoTipoServicio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGeneralInfoTipoServicio.setObjectName("frameGeneralInfoTipoServicio")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameGeneralInfoTipoServicio)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frameInfoTipoServicio = QtWidgets.QFrame(self.frameGeneralInfoTipoServicio)
        self.frameInfoTipoServicio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameInfoTipoServicio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameInfoTipoServicio.setObjectName("frameInfoTipoServicio")
        self.layoutWidget = QtWidgets.QWidget(self.frameInfoTipoServicio)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 70, 371, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.hlInfoTipoServicio = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.hlInfoTipoServicio.setContentsMargins(0, 0, 0, 0)
        self.hlInfoTipoServicio.setObjectName("hlInfoTipoServicio")
        self.labelInfoNombreTipoServicio = QtWidgets.QLabel(self.layoutWidget)
        self.labelInfoNombreTipoServicio.setObjectName("labelInfoNombreTipoServicio")
        self.hlInfoTipoServicio.addWidget(self.labelInfoNombreTipoServicio)
        self.inputInfoNombreTipoServicio = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputInfoNombreTipoServicio.setObjectName("inputInfoNombreTipoServicio")
        self.hlInfoTipoServicio.addWidget(self.inputInfoNombreTipoServicio)
        self.verticalLayout_2.addWidget(self.frameInfoTipoServicio)
        self.frameAccionesInfoTipoServicio = QtWidgets.QFrame(self.frameGeneralInfoTipoServicio)
        self.frameAccionesInfoTipoServicio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameAccionesInfoTipoServicio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameAccionesInfoTipoServicio.setObjectName("frameAccionesInfoTipoServicio")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frameAccionesInfoTipoServicio)
        self.layoutWidget_2.setGeometry(QtCore.QRect(30, 20, 371, 41))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.hlBotonesAccionTipoServicio = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.hlBotonesAccionTipoServicio.setContentsMargins(0, 0, 0, 0)
        self.hlBotonesAccionTipoServicio.setObjectName("hlBotonesAccionTipoServicio")
        self.botonAcualizarInfoTipoServicio = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonAcualizarInfoTipoServicio.sizePolicy().hasHeightForWidth())
        self.botonAcualizarInfoTipoServicio.setSizePolicy(sizePolicy)
        self.botonAcualizarInfoTipoServicio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonAcualizarInfoTipoServicio.setObjectName("botonAcualizarInfoTipoServicio")
        self.hlBotonesAccionTipoServicio.addWidget(self.botonAcualizarInfoTipoServicio)
        self.botonEliminarTipoServicio = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonEliminarTipoServicio.sizePolicy().hasHeightForWidth())
        self.botonEliminarTipoServicio.setSizePolicy(sizePolicy)
        self.botonEliminarTipoServicio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonEliminarTipoServicio.setObjectName("botonEliminarTipoServicio")
        self.hlBotonesAccionTipoServicio.addWidget(self.botonEliminarTipoServicio)
        self.botonCancelarInfoTipoServicio = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonCancelarInfoTipoServicio.sizePolicy().hasHeightForWidth())
        self.botonCancelarInfoTipoServicio.setSizePolicy(sizePolicy)
        self.botonCancelarInfoTipoServicio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonCancelarInfoTipoServicio.setObjectName("botonCancelarInfoTipoServicio")
        self.hlBotonesAccionTipoServicio.addWidget(self.botonCancelarInfoTipoServicio)
        self.verticalLayout_2.addWidget(self.frameAccionesInfoTipoServicio)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout.addWidget(self.frameGeneralInfoTipoServicio)

        self.retranslateUi(VentanaInfoTipoServicio)
        QtCore.QMetaObject.connectSlotsByName(VentanaInfoTipoServicio)

    def retranslateUi(self, VentanaInfoTipoServicio):
        _translate = QtCore.QCoreApplication.translate
        VentanaInfoTipoServicio.setWindowTitle(_translate("VentanaInfoTipoServicio", "Información del tipo de servicio"))
        self.labelInfoNombreTipoServicio.setText(_translate("VentanaInfoTipoServicio", "Nombre del tipo de servicio:"))
        self.botonAcualizarInfoTipoServicio.setText(_translate("VentanaInfoTipoServicio", "Actualizar info"))
        self.botonEliminarTipoServicio.setText(_translate("VentanaInfoTipoServicio", "Eliminar"))
        self.botonCancelarInfoTipoServicio.setText(_translate("VentanaInfoTipoServicio", "Cancelar"))
import qtRecursosIconos_rc
