# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\ventanas\ventanas_qt\VentanaInfoUsuario.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaInfoUsuario(object):
    def setupUi(self, VentanaInfoUsuario):
        VentanaInfoUsuario.setObjectName("VentanaInfoUsuario")
        VentanaInfoUsuario.resize(665, 361)
        VentanaInfoUsuario.setMinimumSize(QtCore.QSize(665, 361))
        VentanaInfoUsuario.setMaximumSize(QtCore.QSize(665, 361))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconos/iconos/icono-app-dgtic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        VentanaInfoUsuario.setWindowIcon(icon)
        VentanaInfoUsuario.setStyleSheet("#VentanaInfoUsuario {\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"#frameGeneralInfoUsuario .QPushButton{\n"
"    color: #ffffff;\n"
"    background-color: #417fd2;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    border-radius: 6px;\n"
"    padding-bottom: 2px;\n"
"    font: 8.5pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"#frameGeneralInfoUsuario .QPushButton::hover{\n"
"    background-color: #5c8bc9;\n"
"}\n"
"\n"
"#frameGeneralInfoUsuario .QPushButton::pressed{\n"
"    background-color: #063c85;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(VentanaInfoUsuario)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameGeneralInfoUsuario = QtWidgets.QFrame(VentanaInfoUsuario)
        self.frameGeneralInfoUsuario.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGeneralInfoUsuario.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGeneralInfoUsuario.setObjectName("frameGeneralInfoUsuario")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameGeneralInfoUsuario)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frameInfoUsuario = QtWidgets.QFrame(self.frameGeneralInfoUsuario)
        self.frameInfoUsuario.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameInfoUsuario.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameInfoUsuario.setObjectName("frameInfoUsuario")
        self.layoutWidget = QtWidgets.QWidget(self.frameInfoUsuario)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 30, 411, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.vlInfoUsuario = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.vlInfoUsuario.setContentsMargins(0, 0, 0, 0)
        self.vlInfoUsuario.setObjectName("vlInfoUsuario")
        self.hlInfoNombreUsuario = QtWidgets.QHBoxLayout()
        self.hlInfoNombreUsuario.setObjectName("hlInfoNombreUsuario")
        self.labelInfoNombreUsuario = QtWidgets.QLabel(self.layoutWidget)
        self.labelInfoNombreUsuario.setObjectName("labelInfoNombreUsuario")
        self.hlInfoNombreUsuario.addWidget(self.labelInfoNombreUsuario)
        self.inputInfoNombreUsuario = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputInfoNombreUsuario.setObjectName("inputInfoNombreUsuario")
        self.hlInfoNombreUsuario.addWidget(self.inputInfoNombreUsuario)
        self.vlInfoUsuario.addLayout(self.hlInfoNombreUsuario)
        self.hlInfoTIpoRol = QtWidgets.QHBoxLayout()
        self.hlInfoTIpoRol.setObjectName("hlInfoTIpoRol")
        self.labelInfoTipoRol = QtWidgets.QLabel(self.layoutWidget)
        self.labelInfoTipoRol.setMaximumSize(QtCore.QSize(115, 16777215))
        self.labelInfoTipoRol.setObjectName("labelInfoTipoRol")
        self.hlInfoTIpoRol.addWidget(self.labelInfoTipoRol)
        self.cbInfoTipoRol = QtWidgets.QComboBox(self.layoutWidget)
        self.cbInfoTipoRol.setObjectName("cbInfoTipoRol")
        self.cbInfoTipoRol.addItem("")
        self.cbInfoTipoRol.addItem("")
        self.hlInfoTIpoRol.addWidget(self.cbInfoTipoRol)
        self.vlInfoUsuario.addLayout(self.hlInfoTIpoRol)
        self.hlInfoClaveUsuario = QtWidgets.QHBoxLayout()
        self.hlInfoClaveUsuario.setObjectName("hlInfoClaveUsuario")
        self.labelInfoClaveUsuario = QtWidgets.QLabel(self.layoutWidget)
        self.labelInfoClaveUsuario.setAlignment(QtCore.Qt.AlignCenter)
        self.labelInfoClaveUsuario.setWordWrap(False)
        self.labelInfoClaveUsuario.setObjectName("labelInfoClaveUsuario")
        self.hlInfoClaveUsuario.addWidget(self.labelInfoClaveUsuario)
        self.inputInfoClaveUsuario = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputInfoClaveUsuario.setObjectName("inputInfoClaveUsuario")
        self.hlInfoClaveUsuario.addWidget(self.inputInfoClaveUsuario)
        self.vlInfoUsuario.addLayout(self.hlInfoClaveUsuario)
        self.verticalLayout_2.addWidget(self.frameInfoUsuario)
        self.frameBotonesAccionUsuario = QtWidgets.QFrame(self.frameGeneralInfoUsuario)
        self.frameBotonesAccionUsuario.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBotonesAccionUsuario.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBotonesAccionUsuario.setObjectName("frameBotonesAccionUsuario")
        self.layoutWidget1 = QtWidgets.QWidget(self.frameBotonesAccionUsuario)
        self.layoutWidget1.setGeometry(QtCore.QRect(120, 30, 371, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.hlBotonesAccionUsuario = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.hlBotonesAccionUsuario.setContentsMargins(0, 0, 0, 0)
        self.hlBotonesAccionUsuario.setObjectName("hlBotonesAccionUsuario")
        self.botonAcualizarInfoUsuario = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonAcualizarInfoUsuario.sizePolicy().hasHeightForWidth())
        self.botonAcualizarInfoUsuario.setSizePolicy(sizePolicy)
        self.botonAcualizarInfoUsuario.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonAcualizarInfoUsuario.setObjectName("botonAcualizarInfoUsuario")
        self.hlBotonesAccionUsuario.addWidget(self.botonAcualizarInfoUsuario)
        self.botonEliminarUsuario = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonEliminarUsuario.sizePolicy().hasHeightForWidth())
        self.botonEliminarUsuario.setSizePolicy(sizePolicy)
        self.botonEliminarUsuario.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonEliminarUsuario.setObjectName("botonEliminarUsuario")
        self.hlBotonesAccionUsuario.addWidget(self.botonEliminarUsuario)
        self.botonCancelarInfoUsuario = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonCancelarInfoUsuario.sizePolicy().hasHeightForWidth())
        self.botonCancelarInfoUsuario.setSizePolicy(sizePolicy)
        self.botonCancelarInfoUsuario.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonCancelarInfoUsuario.setObjectName("botonCancelarInfoUsuario")
        self.hlBotonesAccionUsuario.addWidget(self.botonCancelarInfoUsuario)
        self.verticalLayout_2.addWidget(self.frameBotonesAccionUsuario)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout.addWidget(self.frameGeneralInfoUsuario)

        self.retranslateUi(VentanaInfoUsuario)
        QtCore.QMetaObject.connectSlotsByName(VentanaInfoUsuario)

    def retranslateUi(self, VentanaInfoUsuario):
        _translate = QtCore.QCoreApplication.translate
        VentanaInfoUsuario.setWindowTitle(_translate("VentanaInfoUsuario", "Información del usuario"))
        self.labelInfoNombreUsuario.setText(_translate("VentanaInfoUsuario", "Nombre de usuario:"))
        self.labelInfoTipoRol.setText(_translate("VentanaInfoUsuario", "Tipo de rol:"))
        self.cbInfoTipoRol.setItemText(0, _translate("VentanaInfoUsuario", "ADMINISTRADOR"))
        self.cbInfoTipoRol.setItemText(1, _translate("VentanaInfoUsuario", "ESTANDAR"))
        self.labelInfoClaveUsuario.setText(_translate("VentanaInfoUsuario", "Clave (Dejar vacío para no modificar):"))
        self.botonAcualizarInfoUsuario.setText(_translate("VentanaInfoUsuario", "Actualizar info"))
        self.botonEliminarUsuario.setText(_translate("VentanaInfoUsuario", "Eliminar"))
        self.botonCancelarInfoUsuario.setText(_translate("VentanaInfoUsuario", "Cancelar"))
import qtRecursosIconos_rc
