# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\ventanas\ventanas_qt\VentanaCargaImportacionBd.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaCargaImportacion(object):
    def setupUi(self, VentanaCargaImportacion):
        VentanaCargaImportacion.setObjectName("VentanaCargaImportacion")
        VentanaCargaImportacion.resize(467, 143)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconos/iconos/icono-app-dgtic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        VentanaCargaImportacion.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(VentanaCargaImportacion)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frameGeneralCargaImportacionBd = QtWidgets.QFrame(VentanaCargaImportacion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameGeneralCargaImportacionBd.sizePolicy().hasHeightForWidth())
        self.frameGeneralCargaImportacionBd.setSizePolicy(sizePolicy)
        self.frameGeneralCargaImportacionBd.setMinimumSize(QtCore.QSize(445, 100))
        self.frameGeneralCargaImportacionBd.setMaximumSize(QtCore.QSize(423, 280))
        self.frameGeneralCargaImportacionBd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGeneralCargaImportacionBd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGeneralCargaImportacionBd.setObjectName("frameGeneralCargaImportacionBd")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frameGeneralCargaImportacionBd)
        self.verticalLayout.setObjectName("verticalLayout")
        self.vlCargaImportacionBd = QtWidgets.QVBoxLayout()
        self.vlCargaImportacionBd.setObjectName("vlCargaImportacionBd")
        self.labelImportacionBd = QtWidgets.QLabel(self.frameGeneralCargaImportacionBd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelImportacionBd.sizePolicy().hasHeightForWidth())
        self.labelImportacionBd.setSizePolicy(sizePolicy)
        self.labelImportacionBd.setMinimumSize(QtCore.QSize(0, 0))
        self.labelImportacionBd.setMaximumSize(QtCore.QSize(16777215, 40))
        self.labelImportacionBd.setObjectName("labelImportacionBd")
        self.vlCargaImportacionBd.addWidget(self.labelImportacionBd)
        self.barraProgresoImportacionBd = QtWidgets.QProgressBar(self.frameGeneralCargaImportacionBd)
        self.barraProgresoImportacionBd.setProperty("value", 24)
        self.barraProgresoImportacionBd.setObjectName("barraProgresoImportacionBd")
        self.vlCargaImportacionBd.addWidget(self.barraProgresoImportacionBd)
        self.verticalLayout.addLayout(self.vlCargaImportacionBd)
        self.verticalLayout_2.addWidget(self.frameGeneralCargaImportacionBd, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)

        self.retranslateUi(VentanaCargaImportacion)
        QtCore.QMetaObject.connectSlotsByName(VentanaCargaImportacion)

    def retranslateUi(self, VentanaCargaImportacion):
        _translate = QtCore.QCoreApplication.translate
        VentanaCargaImportacion.setWindowTitle(_translate("VentanaCargaImportacion", "Importando respaldo..."))
        self.labelImportacionBd.setText(_translate("VentanaCargaImportacion", "Cargando datos...."))
import qtRecursosIconos_rc
