# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\ventanas\ventanas_qt\VentanaGenerarReporte.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaGenerarReporte(object):
    def setupUi(self, VentanaGenerarReporte):
        VentanaGenerarReporte.setObjectName("VentanaGenerarReporte")
        VentanaGenerarReporte.resize(400, 355)
        VentanaGenerarReporte.setMinimumSize(QtCore.QSize(400, 355))
        VentanaGenerarReporte.setMaximumSize(QtCore.QSize(400, 355))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconos/iconos/icono-app-dgtic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        VentanaGenerarReporte.setWindowIcon(icon)
        VentanaGenerarReporte.setStyleSheet("#VentanaGenerarReporte {\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"#labelTituloReporte {\n"
"    font-weight: bold;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"#frameGeneralReporte .QPushButton{\n"
"    color: #ffffff;\n"
"    background-color: #417fd2;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    border-radius: 6px;\n"
"    padding-bottom: 2px;\n"
"    font: 8.5pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"#frameGeneralReporte .QPushButton::hover{\n"
"    background-color: #5c8bc9;\n"
"}\n"
"\n"
"#frameGeneralReporte .QPushButton::pressed{\n"
"    background-color: #063c85;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(VentanaGenerarReporte)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameGeneralReporte = QtWidgets.QFrame(VentanaGenerarReporte)
        self.frameGeneralReporte.setMinimumSize(QtCore.QSize(378, 333))
        self.frameGeneralReporte.setMaximumSize(QtCore.QSize(378, 333))
        self.frameGeneralReporte.setStyleSheet("")
        self.frameGeneralReporte.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGeneralReporte.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGeneralReporte.setObjectName("frameGeneralReporte")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameGeneralReporte)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frameOpcionesGenerar = QtWidgets.QFrame(self.frameGeneralReporte)
        self.frameOpcionesGenerar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameOpcionesGenerar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameOpcionesGenerar.setObjectName("frameOpcionesGenerar")
        self.barraProgresoReporte = QtWidgets.QProgressBar(self.frameOpcionesGenerar)
        self.barraProgresoReporte.setGeometry(QtCore.QRect(50, 180, 281, 23))
        self.barraProgresoReporte.setProperty("value", 0)
        self.barraProgresoReporte.setObjectName("barraProgresoReporte")
        self.layoutWidget = QtWidgets.QWidget(self.frameOpcionesGenerar)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 10, 241, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.vlOpcionesGenerarReporte = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.vlOpcionesGenerarReporte.setContentsMargins(0, 0, 0, 0)
        self.vlOpcionesGenerarReporte.setObjectName("vlOpcionesGenerarReporte")
        self.labelTituloReporte = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.labelTituloReporte.setFont(font)
        self.labelTituloReporte.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTituloReporte.setWordWrap(True)
        self.labelTituloReporte.setObjectName("labelTituloReporte")
        self.vlOpcionesGenerarReporte.addWidget(self.labelTituloReporte)
        self.deFechaReporte = QtWidgets.QDateEdit(self.layoutWidget)
        self.deFechaReporte.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.deFechaReporte.setFont(font)
        self.deFechaReporte.setStyleSheet("QDateEdit {\n"
"    qproperty-alignment: AlignCenter;\n"
"}")
        self.deFechaReporte.setObjectName("deFechaReporte")
        self.vlOpcionesGenerarReporte.addWidget(self.deFechaReporte)
        self.verticalLayout_2.addWidget(self.frameOpcionesGenerar)
        self.frameSeccionInferiorReporte = QtWidgets.QFrame(self.frameGeneralReporte)
        self.frameSeccionInferiorReporte.setMaximumSize(QtCore.QSize(16777215, 95))
        self.frameSeccionInferiorReporte.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSeccionInferiorReporte.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSeccionInferiorReporte.setObjectName("frameSeccionInferiorReporte")
        self.labelEstadoReporte = QtWidgets.QLabel(self.frameSeccionInferiorReporte)
        self.labelEstadoReporte.setGeometry(QtCore.QRect(0, 0, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelEstadoReporte.setFont(font)
        self.labelEstadoReporte.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEstadoReporte.setWordWrap(True)
        self.labelEstadoReporte.setObjectName("labelEstadoReporte")
        self.layoutWidget1 = QtWidgets.QWidget(self.frameSeccionInferiorReporte)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 50, 311, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.hlBotonesInferioresReporte = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.hlBotonesInferioresReporte.setContentsMargins(0, 0, 0, 0)
        self.hlBotonesInferioresReporte.setObjectName("hlBotonesInferioresReporte")
        self.botonGenerarReporteServicio = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonGenerarReporteServicio.sizePolicy().hasHeightForWidth())
        self.botonGenerarReporteServicio.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botonGenerarReporteServicio.setFont(font)
        self.botonGenerarReporteServicio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonGenerarReporteServicio.setObjectName("botonGenerarReporteServicio")
        self.hlBotonesInferioresReporte.addWidget(self.botonGenerarReporteServicio)
        self.botonCancelarReporteServicio = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonCancelarReporteServicio.sizePolicy().hasHeightForWidth())
        self.botonCancelarReporteServicio.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botonCancelarReporteServicio.setFont(font)
        self.botonCancelarReporteServicio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonCancelarReporteServicio.setObjectName("botonCancelarReporteServicio")
        self.hlBotonesInferioresReporte.addWidget(self.botonCancelarReporteServicio)
        self.verticalLayout_2.addWidget(self.frameSeccionInferiorReporte)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout.addWidget(self.frameGeneralReporte)

        self.retranslateUi(VentanaGenerarReporte)
        QtCore.QMetaObject.connectSlotsByName(VentanaGenerarReporte)

    def retranslateUi(self, VentanaGenerarReporte):
        _translate = QtCore.QCoreApplication.translate
        VentanaGenerarReporte.setWindowTitle(_translate("VentanaGenerarReporte", "Generar reporte"))
        self.labelTituloReporte.setText(_translate("VentanaGenerarReporte", "Elige el mes y el año del reporte a generar"))
        self.deFechaReporte.setDisplayFormat(_translate("VentanaGenerarReporte", "MM/yyyy"))
        self.labelEstadoReporte.setText(_translate("VentanaGenerarReporte", "Listo para generar"))
        self.botonGenerarReporteServicio.setText(_translate("VentanaGenerarReporte", "Generar reporte"))
        self.botonCancelarReporteServicio.setText(_translate("VentanaGenerarReporte", "Cancelar"))
import qtRecursosIconos_rc
