# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\ventanas\ventanas_qt\VentanaInfoServicio.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventanaInfoServicio(object):
    def setupUi(self, ventanaInfoServicio):
        ventanaInfoServicio.setObjectName("ventanaInfoServicio")
        ventanaInfoServicio.resize(605, 550)
        ventanaInfoServicio.setMinimumSize(QtCore.QSize(605, 453))
        ventanaInfoServicio.setMaximumSize(QtCore.QSize(605, 550))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconos/iconos/icono-app-dgtic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ventanaInfoServicio.setWindowIcon(icon)
        ventanaInfoServicio.setStatusTip("")
        ventanaInfoServicio.setWhatsThis("")
        ventanaInfoServicio.setAccessibleDescription("")
        ventanaInfoServicio.setStyleSheet("#ventanaInfoServicio {\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"#frameGeneralInfoServicio .QPushButton{\n"
"    color: #ffffff;\n"
"    background-color: #417fd2;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    border-radius: 6px;\n"
"    padding-bottom: 2px;\n"
"    font: 8.5pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"#frameGeneralInfoServicio .QPushButton::hover{\n"
"    background-color: #5c8bc9;\n"
"}\n"
"\n"
"#frameGeneralInfoServicio .QPushButton::pressed{\n"
"    background-color: #063c85;\n"
"}")
        ventanaInfoServicio.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(ventanaInfoServicio)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameGeneralInfoServicio = QtWidgets.QFrame(ventanaInfoServicio)
        self.frameGeneralInfoServicio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGeneralInfoServicio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGeneralInfoServicio.setObjectName("frameGeneralInfoServicio")
        self.frameCamposInfoServicio = QtWidgets.QFrame(self.frameGeneralInfoServicio)
        self.frameCamposInfoServicio.setGeometry(QtCore.QRect(10, 10, 570, 391))
        self.frameCamposInfoServicio.setMaximumSize(QtCore.QSize(570, 16777215))
        self.frameCamposInfoServicio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameCamposInfoServicio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCamposInfoServicio.setObjectName("frameCamposInfoServicio")
        self.layoutWidget = QtWidgets.QWidget(self.frameCamposInfoServicio)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 40, 451, 281))
        self.layoutWidget.setObjectName("layoutWidget")
        self.vlCamposInfoServicio = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.vlCamposInfoServicio.setContentsMargins(0, 0, 0, 0)
        self.vlCamposInfoServicio.setObjectName("vlCamposInfoServicio")
        self.hlFechaServicio = QtWidgets.QHBoxLayout()
        self.hlFechaServicio.setObjectName("hlFechaServicio")
        self.labelInfoFechaServicio = QtWidgets.QLabel(self.layoutWidget)
        self.labelInfoFechaServicio.setObjectName("labelInfoFechaServicio")
        self.hlFechaServicio.addWidget(self.labelInfoFechaServicio)
        self.deInfoFechaServicio = QtWidgets.QDateEdit(self.layoutWidget)
        self.deInfoFechaServicio.setCalendarPopup(True)
        self.deInfoFechaServicio.setObjectName("deInfoFechaServicio")
        self.hlFechaServicio.addWidget(self.deInfoFechaServicio)
        self.vlCamposInfoServicio.addLayout(self.hlFechaServicio)
        self.hlNombreDepartamento = QtWidgets.QHBoxLayout()
        self.hlNombreDepartamento.setObjectName("hlNombreDepartamento")
        self.labelInfoNombreDepartamento = QtWidgets.QLabel(self.layoutWidget)
        self.labelInfoNombreDepartamento.setObjectName("labelInfoNombreDepartamento")
        self.hlNombreDepartamento.addWidget(self.labelInfoNombreDepartamento)
        spacerItem = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.hlNombreDepartamento.addItem(spacerItem)
        self.inputInfoNombreDepartamento = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputInfoNombreDepartamento.setObjectName("inputInfoNombreDepartamento")
        self.hlNombreDepartamento.addWidget(self.inputInfoNombreDepartamento)
        self.vlCamposInfoServicio.addLayout(self.hlNombreDepartamento)
        self.hlFallaPresenta = QtWidgets.QHBoxLayout()
        self.hlFallaPresenta.setObjectName("hlFallaPresenta")
        self.labelInfoFallaPresenta = QtWidgets.QLabel(self.layoutWidget)
        self.labelInfoFallaPresenta.setObjectName("labelInfoFallaPresenta")
        self.hlFallaPresenta.addWidget(self.labelInfoFallaPresenta)
        spacerItem1 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.hlFallaPresenta.addItem(spacerItem1)
        self.inputInfoFallaPresenta = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputInfoFallaPresenta.setObjectName("inputInfoFallaPresenta")
        self.hlFallaPresenta.addWidget(self.inputInfoFallaPresenta)
        self.vlCamposInfoServicio.addLayout(self.hlFallaPresenta)
        self.hlServicioPrestado = QtWidgets.QHBoxLayout()
        self.hlServicioPrestado.setObjectName("hlServicioPrestado")
        self.labelInfoServicioPrestado = QtWidgets.QLabel(self.layoutWidget)
        self.labelInfoServicioPrestado.setObjectName("labelInfoServicioPrestado")
        self.hlServicioPrestado.addWidget(self.labelInfoServicioPrestado)
        spacerItem2 = QtWidgets.QSpacerItem(67, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.hlServicioPrestado.addItem(spacerItem2)
        self.inputInfoServicioPrestado = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputInfoServicioPrestado.setObjectName("inputInfoServicioPrestado")
        self.hlServicioPrestado.addWidget(self.inputInfoServicioPrestado)
        self.vlCamposInfoServicio.addLayout(self.hlServicioPrestado)
        self.hlNombresTecnicos = QtWidgets.QHBoxLayout()
        self.hlNombresTecnicos.setObjectName("hlNombresTecnicos")
        self.labelInfoNombresTecnicos = QtWidgets.QLabel(self.layoutWidget)
        self.labelInfoNombresTecnicos.setObjectName("labelInfoNombresTecnicos")
        self.hlNombresTecnicos.addWidget(self.labelInfoNombresTecnicos)
        spacerItem3 = QtWidgets.QSpacerItem(33, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.hlNombresTecnicos.addItem(spacerItem3)
        self.inputInfoNombresTecnicos = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputInfoNombresTecnicos.setObjectName("inputInfoNombresTecnicos")
        self.hlNombresTecnicos.addWidget(self.inputInfoNombresTecnicos)
        self.vlCamposInfoServicio.addLayout(self.hlNombresTecnicos)
        self.vlInfoObservacionesAdicionales = QtWidgets.QVBoxLayout()
        self.vlInfoObservacionesAdicionales.setObjectName("vlInfoObservacionesAdicionales")
        self.labelInfoObservacionesAdicionales = QtWidgets.QLabel(self.layoutWidget)
        self.labelInfoObservacionesAdicionales.setObjectName("labelInfoObservacionesAdicionales")
        self.vlInfoObservacionesAdicionales.addWidget(self.labelInfoObservacionesAdicionales)
        self.teInfoObservacionesAdicionales = QtWidgets.QTextEdit(self.layoutWidget)
        self.teInfoObservacionesAdicionales.setObjectName("teInfoObservacionesAdicionales")
        self.vlInfoObservacionesAdicionales.addWidget(self.teInfoObservacionesAdicionales)
        self.vlCamposInfoServicio.addLayout(self.vlInfoObservacionesAdicionales)
        self.frameBotonesAccionServicio = QtWidgets.QFrame(self.frameGeneralInfoServicio)
        self.frameBotonesAccionServicio.setGeometry(QtCore.QRect(10, 420, 570, 101))
        self.frameBotonesAccionServicio.setMaximumSize(QtCore.QSize(570, 16777215))
        self.frameBotonesAccionServicio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBotonesAccionServicio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBotonesAccionServicio.setObjectName("frameBotonesAccionServicio")
        self.layoutWidget1 = QtWidgets.QWidget(self.frameBotonesAccionServicio)
        self.layoutWidget1.setGeometry(QtCore.QRect(90, 30, 371, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.hlBotonesAccionServicio = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.hlBotonesAccionServicio.setContentsMargins(0, 0, 0, 0)
        self.hlBotonesAccionServicio.setObjectName("hlBotonesAccionServicio")
        self.botonAcualizarInfoServicio = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonAcualizarInfoServicio.sizePolicy().hasHeightForWidth())
        self.botonAcualizarInfoServicio.setSizePolicy(sizePolicy)
        self.botonAcualizarInfoServicio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonAcualizarInfoServicio.setObjectName("botonAcualizarInfoServicio")
        self.hlBotonesAccionServicio.addWidget(self.botonAcualizarInfoServicio)
        self.botonEliminarServicio = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonEliminarServicio.sizePolicy().hasHeightForWidth())
        self.botonEliminarServicio.setSizePolicy(sizePolicy)
        self.botonEliminarServicio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonEliminarServicio.setObjectName("botonEliminarServicio")
        self.hlBotonesAccionServicio.addWidget(self.botonEliminarServicio)
        self.botonCancelar = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonCancelar.sizePolicy().hasHeightForWidth())
        self.botonCancelar.setSizePolicy(sizePolicy)
        self.botonCancelar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonCancelar.setObjectName("botonCancelar")
        self.hlBotonesAccionServicio.addWidget(self.botonCancelar)
        self.verticalLayout.addWidget(self.frameGeneralInfoServicio)

        self.retranslateUi(ventanaInfoServicio)
        QtCore.QMetaObject.connectSlotsByName(ventanaInfoServicio)

    def retranslateUi(self, ventanaInfoServicio):
        _translate = QtCore.QCoreApplication.translate
        ventanaInfoServicio.setWindowTitle(_translate("ventanaInfoServicio", "Información del servicio"))
        self.labelInfoFechaServicio.setText(_translate("ventanaInfoServicio", "Fecha del servicio:"))
        self.labelInfoNombreDepartamento.setText(_translate("ventanaInfoServicio", "Nombre del departamento:"))
        self.labelInfoFallaPresenta.setText(_translate("ventanaInfoServicio", "Falla que presenta:"))
        self.labelInfoServicioPrestado.setText(_translate("ventanaInfoServicio", "Servicio prestado:"))
        self.labelInfoNombresTecnicos.setText(_translate("ventanaInfoServicio", "Nombre de los técnicos:"))
        self.labelInfoObservacionesAdicionales.setText(_translate("ventanaInfoServicio", "Observaciones adicionales:"))
        self.botonAcualizarInfoServicio.setText(_translate("ventanaInfoServicio", "Actualizar info"))
        self.botonEliminarServicio.setText(_translate("ventanaInfoServicio", "Eliminar"))
        self.botonCancelar.setText(_translate("ventanaInfoServicio", "Cancelar"))
import qtRecursosIconos_rc
