# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\ventanas\ventanas_qt\VentanaInfoDepartamento.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaInfoDepartamento(object):
    def setupUi(self, VentanaInfoDepartamento):
        VentanaInfoDepartamento.setObjectName("VentanaInfoDepartamento")
        VentanaInfoDepartamento.resize(475, 268)
        VentanaInfoDepartamento.setMinimumSize(QtCore.QSize(475, 268))
        VentanaInfoDepartamento.setMaximumSize(QtCore.QSize(475, 268))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconos/iconos/icono-app-dgtic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        VentanaInfoDepartamento.setWindowIcon(icon)
        VentanaInfoDepartamento.setStyleSheet("#VentanaInfoDepartamento {\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"#frameGeneralInfoDepartamento .QPushButton{\n"
"    color: #ffffff;\n"
"    background-color: #417fd2;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    border-radius: 6px;\n"
"    padding-bottom: 2px;\n"
"    font: 8.5pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"#frameGeneralInfoDepartamento .QPushButton::hover{\n"
"    background-color: #5c8bc9;\n"
"}\n"
"\n"
"#frameGeneralInfoDepartamento .QPushButton::pressed{\n"
"    background-color: #063c85;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(VentanaInfoDepartamento)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameGeneralInfoDepartamento = QtWidgets.QFrame(VentanaInfoDepartamento)
        self.frameGeneralInfoDepartamento.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGeneralInfoDepartamento.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGeneralInfoDepartamento.setObjectName("frameGeneralInfoDepartamento")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameGeneralInfoDepartamento)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frameInfoDepartamento = QtWidgets.QFrame(self.frameGeneralInfoDepartamento)
        self.frameInfoDepartamento.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameInfoDepartamento.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameInfoDepartamento.setObjectName("frameInfoDepartamento")
        self.layoutWidget = QtWidgets.QWidget(self.frameInfoDepartamento)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 70, 371, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.hlInfoDepartamento = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.hlInfoDepartamento.setContentsMargins(0, 0, 0, 0)
        self.hlInfoDepartamento.setObjectName("hlInfoDepartamento")
        self.labelInfoNombreDepartamento = QtWidgets.QLabel(self.layoutWidget)
        self.labelInfoNombreDepartamento.setObjectName("labelInfoNombreDepartamento")
        self.hlInfoDepartamento.addWidget(self.labelInfoNombreDepartamento)
        self.inputInfoNombreDepartamento = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputInfoNombreDepartamento.setObjectName("inputInfoNombreDepartamento")
        self.hlInfoDepartamento.addWidget(self.inputInfoNombreDepartamento)
        self.verticalLayout_2.addWidget(self.frameInfoDepartamento)
        self.frameAccionesInfoDepartamento = QtWidgets.QFrame(self.frameGeneralInfoDepartamento)
        self.frameAccionesInfoDepartamento.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameAccionesInfoDepartamento.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameAccionesInfoDepartamento.setObjectName("frameAccionesInfoDepartamento")
        self.layoutWidget1 = QtWidgets.QWidget(self.frameAccionesInfoDepartamento)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 20, 371, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.hlBotonesAccionDepartamento = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.hlBotonesAccionDepartamento.setContentsMargins(0, 0, 0, 0)
        self.hlBotonesAccionDepartamento.setObjectName("hlBotonesAccionDepartamento")
        self.botonAcualizarInfoDepartamento = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonAcualizarInfoDepartamento.sizePolicy().hasHeightForWidth())
        self.botonAcualizarInfoDepartamento.setSizePolicy(sizePolicy)
        self.botonAcualizarInfoDepartamento.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonAcualizarInfoDepartamento.setObjectName("botonAcualizarInfoDepartamento")
        self.hlBotonesAccionDepartamento.addWidget(self.botonAcualizarInfoDepartamento)
        self.botonEliminarDepartamento = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonEliminarDepartamento.sizePolicy().hasHeightForWidth())
        self.botonEliminarDepartamento.setSizePolicy(sizePolicy)
        self.botonEliminarDepartamento.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonEliminarDepartamento.setObjectName("botonEliminarDepartamento")
        self.hlBotonesAccionDepartamento.addWidget(self.botonEliminarDepartamento)
        self.botonCancelarInfoDepartamento = QtWidgets.QPushButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonCancelarInfoDepartamento.sizePolicy().hasHeightForWidth())
        self.botonCancelarInfoDepartamento.setSizePolicy(sizePolicy)
        self.botonCancelarInfoDepartamento.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonCancelarInfoDepartamento.setObjectName("botonCancelarInfoDepartamento")
        self.hlBotonesAccionDepartamento.addWidget(self.botonCancelarInfoDepartamento)
        self.verticalLayout_2.addWidget(self.frameAccionesInfoDepartamento)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout.addWidget(self.frameGeneralInfoDepartamento)

        self.retranslateUi(VentanaInfoDepartamento)
        QtCore.QMetaObject.connectSlotsByName(VentanaInfoDepartamento)

    def retranslateUi(self, VentanaInfoDepartamento):
        _translate = QtCore.QCoreApplication.translate
        VentanaInfoDepartamento.setWindowTitle(_translate("VentanaInfoDepartamento", "Información del departamento"))
        self.labelInfoNombreDepartamento.setText(_translate("VentanaInfoDepartamento", "Nombre del departamento:"))
        self.botonAcualizarInfoDepartamento.setText(_translate("VentanaInfoDepartamento", "Actualizar info"))
        self.botonEliminarDepartamento.setText(_translate("VentanaInfoDepartamento", "Eliminar"))
        self.botonCancelarInfoDepartamento.setText(_translate("VentanaInfoDepartamento", "Cancelar"))
import qtRecursosIconos_rc
