# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\vistas\vistas_qt\VentanaPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ventanaPrincipal(object):
    def setupUi(self, ventanaPrincipal):
        ventanaPrincipal.setObjectName("ventanaPrincipal")
        ventanaPrincipal.resize(1300, 731)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ventanaPrincipal.sizePolicy().hasHeightForWidth())
        ventanaPrincipal.setSizePolicy(sizePolicy)
        ventanaPrincipal.setMinimumSize(QtCore.QSize(1300, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconos/iconos/icono-app-dgtic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ventanaPrincipal.setWindowIcon(icon)
        ventanaPrincipal.setStyleSheet("\n"
"#ventanaPrincipal {\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:1, stop:0.477612 rgba(72, 111, 182, 255), stop:0.751244 rgba(31, 72, 133, 255))\n"
"}\n"
"\n"
"\n"
"/* BOTÓN DE MANUAL DE USUARIO  */\n"
"\n"
"#botonManualUsuarioSeccionIniciarSesion,\n"
"#frameSuperior #botonManualUsuarioSeccionApp,\n"
"#frameSeccionRegistrarDepartamento #botonManualUsuarioSeccionDepartamentos,\n"
"#frameSeccionRegistrarUsuario #botonManualUsuarioSeccionUsuarios,\n"
"#frameSuperiorTipoServicio #botonManualUsuarioSeccionTipoServicio,\n"
"#frameSuperiorCategoriaTipoServicio #botonManualUsuarioSeccionCategoriaTipoServicio {\n"
"    background-image: url(:/iconos/iconos/help.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-color: #fff;\n"
"    border: 1px solid #000000;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"\n"
"#botonManualUsuarioSeccionIniciarSesion::hover,\n"
"#frameSuperior #botonManualUsuarioSeccionApp::hover,\n"
"#frameSeccionRegistrarDepartamento #botonManualUsuarioSeccionDepartamentos::hover,\n"
"#frameSeccionRegistrarUsuario #botonManualUsuarioSeccionUsuarios::hover,\n"
"#frameSuperiorTipoServicio #botonManualUsuarioSeccionTipoServicio::hover,\n"
"#frameSuperiorCategoriaTipoServicio #botonManualUsuarioSeccionCategoriaTipoServicio::hover {\n"
"    background-color: #dadada;\n"
"}\n"
"\n"
"\n"
"#botonManualUsuarioSeccionIniciarSesion::pressed,\n"
"#frameSuperior #botonManualUsuarioSeccionApp::pressed,\n"
"#frameSeccionRegistrarDepartamento #botonManualUsuarioSeccionDepartamentos::pressed,\n"
"#frameSeccionRegistrarUsuario #botonManualUsuarioSeccionUsuarios::pressed,\n"
"#frameSuperiorTipoServicio #botonManualUsuarioSeccionTipoServicio::pressed {\n"
"    background-color: #a3a3a3;\n"
"}\n"
"\n"
"\n"
"/* PÁGINA DE INICIAR SESIÓN */\n"
"\n"
"#frameCamposInicioSesion {\n"
"    background-color: rgb(229, 229, 229);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#labelTituloIniciarSesion {\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#labelNombreUsuario,\n"
"#labelClaveUsuario {\n"
"    font-size: 17px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QWidget{\n"
"    font: 10pt \"Arial\";\n"
"}\n"
"\n"
"#botonAcceder{\n"
"    font: 10pt \"Arial\";\n"
"    color: #ffffff;\n"
"    background-color: #115ad3;\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"    padding-bottom: 2px;\n"
"}\n"
"\n"
"#botonAcceder::hover{\n"
"    background-color: #5c8bc9;\n"
"}\n"
"\n"
"#botonAcceder::pressed{\n"
"    background-color: #063c85;\n"
"}\n"
"\n"
"\n"
"\n"
"/* PÁGINA APP*/\n"
"\n"
"#frameApp{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid #000000;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"#frameInferior .QPushButton{\n"
"    color: #ffffff;\n"
"    background-color: #417fd2;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"    padding-bottom: 2px;\n"
"    font: 10pt \"Arial\";\n"
"}\n"
"\n"
"#frameInferior .QPushButton::hover{\n"
"    background-color: #5c8bc9;\n"
"}\n"
"\n"
"#frameInferior .QPushButton::pressed{\n"
"    background-color: #063c85;\n"
"}\n"
"\n"
"#frameSuperior .QToolButton{\n"
"    color: #ffffff;\n"
"    background-color: #417fd2;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"    padding-bottom: 2px;\n"
"    font: 9pt \"Segoe UI\";\n"
"}\n"
"\n"
"#frameSuperior .QToolButton::hover{\n"
"    background-color: #5c8bc9;\n"
"}\n"
"\n"
"#frameSuperior .QToolButton::pressed{\n"
"    background-color: #063c85;\n"
"}\n"
"\n"
"\n"
"#frameSuperior .QPushButton{\n"
"    color: #ffffff;\n"
"    background-color: #417fd2;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"    padding-bottom: 2px;\n"
"    font: 10pt \"Arial\";\n"
"}\n"
"\n"
"#frameSuperior .QPushButton::hover{\n"
"    background-color: #5c8bc9;\n"
"}\n"
"\n"
"#frameSuperior .QPushButton::pressed{\n"
"    background-color: #063c85;\n"
"}\n"
"\n"
"#frameSuperior #botonRefrescarApp{\n"
"    background-color: #c8c8c8;\n"
"}\n"
"\n"
"\n"
"#frameSuperior #botonRefrescarApp::hover{\n"
"    background-color: #dadada;\n"
"}\n"
"\n"
"#frameSuperior #botonRefrescarApp::pressed{\n"
"    background-color: #a3a3a3;\n"
"}\n"
"\n"
"\n"
"\n"
"/* PÁGINA DEPARTAMENTOS*/\n"
"\n"
"#frameGeneralDepartamentos{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid #000000;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"#frameSeccionRegistrarDepartamento .QPushButton,\n"
"#frameInferiorSeccionDepartamentos .QPushButton {\n"
"    color: #ffffff;\n"
"    background-color: #417fd2;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    border-radius: 6px;\n"
"    padding-bottom: 2px;\n"
"    font: 10pt \"Arial\";\n"
"}\n"
"\n"
"#frameSeccionRegistrarDepartamento .QPushButton::hover,\n"
"#frameInferiorSeccionDepartamentos .QPushButton::hover{\n"
"    background-color: #5c8bc9;\n"
"}\n"
"\n"
"#frameSeccionRegistrarDepartamento .QPushButton::pressed,\n"
"#frameInferiorSeccionDepartamentos .QPushButton::pressed{\n"
"    background-color: #063c85;\n"
"}\n"
"\n"
"#labelTituloRegistrarDepartamento {\n"
"    font-weight: bold;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"#frameSeccionRegistrarDepartamento #botonRefrescarDepartamentos{\n"
"    background-color: #c8c8c8;\n"
"}\n"
"\n"
"#frameSeccionRegistrarDepartamento #botonRefrescarDepartamentos::hover{\n"
"    background-color: #dadada;\n"
"}\n"
"\n"
"#frameSeccionRegistrarDepartamento #botonRefrescarDepartamentos::pressed{\n"
"    background-color: #a3a3a3;\n"
"}\n"
"\n"
"\n"
"\n"
"/* PÁGINA USUARIOS*/\n"
"\n"
"#frameGeneralUsuarios{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid #000000;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"#frameSeccionRegistrarUsuario .QPushButton,\n"
"#frameInferiorSeccionUsuarios .QPushButton {\n"
"    color: #ffffff;\n"
"    background-color: #417fd2;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    border-radius: 6px;\n"
"    padding-bottom: 2px;\n"
"    font: 10pt \"Arial\";\n"
"}\n"
"\n"
"#labelTituloRegistrarUsuario {\n"
"    font-weight: bold;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"#frameSeccionRegistrarUsuario .QPushButton::hover,\n"
"#frameInferiorSeccionUsuarios .QPushButton::hover{\n"
"    background-color: #5c8bc9;\n"
"}\n"
"\n"
"#frameSeccionRegistrarUsuario .QPushButton::pressed,\n"
"#frameInferiorSeccionUsuarios .QPushButton::pressed{\n"
"    background-color: #063c85;\n"
"}\n"
"\n"
"#frameSeccionRegistrarUsuario #botonRefrescarUsuarios{\n"
"    background-color: #c8c8c8;\n"
"}\n"
"\n"
"#frameSeccionRegistrarUsuario #botonRefrescarUsuarios::hover{\n"
"    background-color: #dadada;\n"
"}\n"
"\n"
"#frameSeccionRegistrarUsuario #botonRefrescarUsuarios::pressed{\n"
"    background-color: #a3a3a3;\n"
"}\n"
"\n"
"\n"
"\n"
"/* PÁGINA TIPO DE SERVICIO*/\n"
"\n"
"#frameGeneralTipoServicio{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid #000000;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"#frameSuperiorTipoServicio .QPushButton,\n"
"#frameInferiorTipoServicio .QPushButton {\n"
"    color: #ffffff;\n"
"    background-color: #417fd2;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    border-radius: 6px;\n"
"    padding-bottom: 2px;\n"
"    font: 10pt \"Arial\";\n"
"}\n"
"\n"
"#frameSuperiorTipoServicio .QToolButton{\n"
"    color: #ffffff;\n"
"    background-color: #417fd2;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"    padding-bottom: 2px;\n"
"    font: 9pt \"Segoe UI\";\n"
"}\n"
"\n"
"#frameSuperiorTipoServicio .QToolButton::hover{\n"
"    background-color: #5c8bc9;\n"
"}\n"
"\n"
"#frameSuperiorTipoServicio .QToolButton::pressed{\n"
"    background-color: #063c85;\n"
"}\n"
"\n"
"#labelTituloRegistrarTipoServicio {\n"
"    font-weight: bold;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"#frameSuperiorTipoServicio .QPushButton::hover,\n"
"#frameInferiorTipoServicio .QPushButton::hover{\n"
"    background-color: #5c8bc9;\n"
"}\n"
"\n"
"#frameSuperiorTipoServicio .QPushButton::pressed,\n"
"#frameInferiorTipoServicio .QPushButton::pressed{\n"
"    background-color: #063c85;\n"
"}\n"
"\n"
"#frameSuperiorTipoServicio #botonRefrescarTiposServicio{\n"
"    background-color: #c8c8c8;\n"
"}\n"
"\n"
"#frameSuperiorTipoServicio #botonRefrescarTiposServicio::hover{\n"
"    background-color: #dadada;\n"
"}\n"
"\n"
"#frameSuperiorTipoServicio #botonRefrescarTiposServicio::pressed{\n"
"    background-color: #a3a3a3;\n"
"}\n"
"\n"
"\n"
"\n"
"/* PÁGINA CATEGORÍA DE TIPO DE SERVICIO*/\n"
"\n"
"#frameGeneralCategoriaTipoServicio{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 1px solid #000000;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"#frameSuperiorCategoriaTipoServicio .QPushButton,\n"
"#frameInferiorCategoriaTipoServicio .QPushButton {\n"
"    color: #ffffff;\n"
"    background-color: #417fd2;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    border-radius: 6px;\n"
"    padding-bottom: 2px;\n"
"    font: 10pt \"Arial\";\n"
"}\n"
"\n"
"#labelTituloRegistrarCategoriaTipoServicio {\n"
"    font-weight: bold;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"#frameSuperiorCategoriaTipoServicio .QPushButton::hover,\n"
"#frameInferiorCategoriaTipoServicio .QPushButton::hover{\n"
"    background-color: #5c8bc9;\n"
"}\n"
"\n"
"#frameSuperiorCategoriaTipoServicio .QPushButton::pressed,\n"
"#frameInferiorCategoriaTipoServicio .QPushButton::pressed{\n"
"    background-color: #063c85;\n"
"}\n"
"\n"
"#frameSuperiorCategoriaTipoServicio #botonRefrescarCategoriaTiposServicio{\n"
"    background-color: #c8c8c8;\n"
"}\n"
"\n"
"#frameSuperiorCategoriaTipoServicio #botonRefrescarCategoriaTiposServicio::hover{\n"
"    background-color: #dadada;\n"
"}\n"
"\n"
"#frameSuperiorCategoriaTipoServicio #botonRefrescarCategoriaTiposServicio::pressed{\n"
"    background-color: #a3a3a3;\n"
"}")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(ventanaPrincipal)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.ventanas = QtWidgets.QStackedWidget(ventanaPrincipal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ventanas.sizePolicy().hasHeightForWidth())
        self.ventanas.setSizePolicy(sizePolicy)
        self.ventanas.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ventanas.setObjectName("ventanas")
        self.paginaIniciarSesion = QtWidgets.QWidget()
        self.paginaIniciarSesion.setStyleSheet("")
        self.paginaIniciarSesion.setObjectName("paginaIniciarSesion")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.paginaIniciarSesion)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameGeneralIniciarSesion = QtWidgets.QFrame(self.paginaIniciarSesion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameGeneralIniciarSesion.sizePolicy().hasHeightForWidth())
        self.frameGeneralIniciarSesion.setSizePolicy(sizePolicy)
        self.frameGeneralIniciarSesion.setStyleSheet("")
        self.frameGeneralIniciarSesion.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGeneralIniciarSesion.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGeneralIniciarSesion.setObjectName("frameGeneralIniciarSesion")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameGeneralIniciarSesion)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameInicioSesion = QtWidgets.QFrame(self.frameGeneralIniciarSesion)
        self.frameInicioSesion.setMinimumSize(QtCore.QSize(613, 633))
        self.frameInicioSesion.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameInicioSesion.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameInicioSesion.setObjectName("frameInicioSesion")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frameInicioSesion)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frameCamposInicioSesion = QtWidgets.QFrame(self.frameInicioSesion)
        self.frameCamposInicioSesion.setMinimumSize(QtCore.QSize(541, 609))
        self.frameCamposInicioSesion.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameCamposInicioSesion.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameCamposInicioSesion.setObjectName("frameCamposInicioSesion")
        self.botonAcceder = QtWidgets.QPushButton(self.frameCamposInicioSesion)
        self.botonAcceder.setEnabled(True)
        self.botonAcceder.setGeometry(QtCore.QRect(190, 480, 171, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonAcceder.sizePolicy().hasHeightForWidth())
        self.botonAcceder.setSizePolicy(sizePolicy)
        self.botonAcceder.setMinimumSize(QtCore.QSize(120, 35))
        self.botonAcceder.setMaximumSize(QtCore.QSize(180, 35))
        self.botonAcceder.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonAcceder.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonAcceder.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/iconos/iconos/icono-iniciar-sesion.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonAcceder.setIcon(icon1)
        self.botonAcceder.setIconSize(QtCore.QSize(24, 24))
        self.botonAcceder.setObjectName("botonAcceder")
        self.layoutWidget = QtWidgets.QWidget(self.frameCamposInicioSesion)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 90, 321, 351))
        self.layoutWidget.setObjectName("layoutWidget")
        self.vlCamposIniciarSesion = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.vlCamposIniciarSesion.setContentsMargins(0, 0, 0, 0)
        self.vlCamposIniciarSesion.setSpacing(24)
        self.vlCamposIniciarSesion.setObjectName("vlCamposIniciarSesion")
        self.labelTituloIniciarSesion = QtWidgets.QLabel(self.layoutWidget)
        self.labelTituloIniciarSesion.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTituloIniciarSesion.setObjectName("labelTituloIniciarSesion")
        self.vlCamposIniciarSesion.addWidget(self.labelTituloIniciarSesion)
        self.vlCampoNombreUsuario = QtWidgets.QVBoxLayout()
        self.vlCampoNombreUsuario.setObjectName("vlCampoNombreUsuario")
        self.labelNombreUsuario = QtWidgets.QLabel(self.layoutWidget)
        self.labelNombreUsuario.setObjectName("labelNombreUsuario")
        self.vlCampoNombreUsuario.addWidget(self.labelNombreUsuario)
        self.inputNombreUsuario = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputNombreUsuario.setMinimumSize(QtCore.QSize(257, 32))
        self.inputNombreUsuario.setMaximumSize(QtCore.QSize(16777215, 32))
        self.inputNombreUsuario.setStyleSheet("background-image: url(:/iconos/iconos/user.png);\n"
"background-position: left;\n"
"background-repeat: no-repeat;")
        self.inputNombreUsuario.setAlignment(QtCore.Qt.AlignCenter)
        self.inputNombreUsuario.setObjectName("inputNombreUsuario")
        self.vlCampoNombreUsuario.addWidget(self.inputNombreUsuario)
        self.vlCamposIniciarSesion.addLayout(self.vlCampoNombreUsuario)
        self.vlCampoClave = QtWidgets.QVBoxLayout()
        self.vlCampoClave.setObjectName("vlCampoClave")
        self.labelClaveUsuario = QtWidgets.QLabel(self.layoutWidget)
        self.labelClaveUsuario.setObjectName("labelClaveUsuario")
        self.vlCampoClave.addWidget(self.labelClaveUsuario)
        self.inputClaveUsuario = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputClaveUsuario.setMinimumSize(QtCore.QSize(257, 32))
        self.inputClaveUsuario.setMaximumSize(QtCore.QSize(16777215, 32))
        self.inputClaveUsuario.setStyleSheet("background-image: url(:/iconos/iconos/padlock.png);\n"
"background-position: left;\n"
"background-repeat: no-repeat;\n"
"")
        self.inputClaveUsuario.setAlignment(QtCore.Qt.AlignCenter)
        self.inputClaveUsuario.setObjectName("inputClaveUsuario")
        self.vlCampoClave.addWidget(self.inputClaveUsuario)
        self.vlCamposIniciarSesion.addLayout(self.vlCampoClave)
        self.botonManualUsuarioSeccionIniciarSesion = QtWidgets.QPushButton(self.frameCamposInicioSesion)
        self.botonManualUsuarioSeccionIniciarSesion.setGeometry(QtCore.QRect(480, 10, 40, 40))
        self.botonManualUsuarioSeccionIniciarSesion.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonManualUsuarioSeccionIniciarSesion.setFocusPolicy(QtCore.Qt.NoFocus)
        self.botonManualUsuarioSeccionIniciarSesion.setStyleSheet("")
        self.botonManualUsuarioSeccionIniciarSesion.setText("")
        self.botonManualUsuarioSeccionIniciarSesion.setObjectName("botonManualUsuarioSeccionIniciarSesion")
        self.verticalLayout_11.addWidget(self.frameCamposInicioSesion, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout.addWidget(self.frameInicioSesion, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frameLogoDepartamento = QtWidgets.QFrame(self.frameGeneralIniciarSesion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameLogoDepartamento.sizePolicy().hasHeightForWidth())
        self.frameLogoDepartamento.setSizePolicy(sizePolicy)
        self.frameLogoDepartamento.setMinimumSize(QtCore.QSize(612, 663))
        self.frameLogoDepartamento.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frameLogoDepartamento.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLogoDepartamento.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLogoDepartamento.setObjectName("frameLogoDepartamento")
        self.labelImgLogo = QtWidgets.QLabel(self.frameLogoDepartamento)
        self.labelImgLogo.setGeometry(QtCore.QRect(90, 180, 441, 401))
        self.labelImgLogo.setText("")
        self.labelImgLogo.setPixmap(QtGui.QPixmap(":/logos/logos/logo_dgtic.png"))
        self.labelImgLogo.setScaledContents(True)
        self.labelImgLogo.setObjectName("labelImgLogo")
        self.horizontalLayout.addWidget(self.frameLogoDepartamento, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frameGeneralIniciarSesion, 0, QtCore.Qt.AlignVCenter)
        self.ventanas.addWidget(self.paginaIniciarSesion)
        self.paginaApp = QtWidgets.QWidget()
        self.paginaApp.setStyleSheet("")
        self.paginaApp.setObjectName("paginaApp")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.paginaApp)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frameApp = QtWidgets.QFrame(self.paginaApp)
        self.frameApp.setStyleSheet("")
        self.frameApp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameApp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameApp.setObjectName("frameApp")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frameApp)
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frameSuperior = QtWidgets.QFrame(self.frameApp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameSuperior.sizePolicy().hasHeightForWidth())
        self.frameSuperior.setSizePolicy(sizePolicy)
        self.frameSuperior.setMinimumSize(QtCore.QSize(1150, 250))
        self.frameSuperior.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frameSuperior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSuperior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSuperior.setObjectName("frameSuperior")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frameSuperior)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.vlRegistroYFiltroServicio = QtWidgets.QVBoxLayout()
        self.vlRegistroYFiltroServicio.setObjectName("vlRegistroYFiltroServicio")
        self.hlRegistrarServicio = QtWidgets.QHBoxLayout()
        self.hlRegistrarServicio.setObjectName("hlRegistrarServicio")
        self.vlRegistrarDepYFalla = QtWidgets.QVBoxLayout()
        self.vlRegistrarDepYFalla.setObjectName("vlRegistrarDepYFalla")
        self.glCampoRegistrarNombreDep = QtWidgets.QGridLayout()
        self.glCampoRegistrarNombreDep.setObjectName("glCampoRegistrarNombreDep")
        self.labelDepartamento = QtWidgets.QLabel(self.frameSuperior)
        self.labelDepartamento.setObjectName("labelDepartamento")
        self.glCampoRegistrarNombreDep.addWidget(self.labelDepartamento, 0, 1, 1, 1)
        self.inputDepartamento = QtWidgets.QLineEdit(self.frameSuperior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputDepartamento.sizePolicy().hasHeightForWidth())
        self.inputDepartamento.setSizePolicy(sizePolicy)
        self.inputDepartamento.setMinimumSize(QtCore.QSize(250, 27))
        self.inputDepartamento.setStyleSheet("margin-right: 5px;")
        self.inputDepartamento.setInputMethodHints(QtCore.Qt.ImhNone)
        self.inputDepartamento.setClearButtonEnabled(False)
        self.inputDepartamento.setObjectName("inputDepartamento")
        self.glCampoRegistrarNombreDep.addWidget(self.inputDepartamento, 1, 1, 1, 1)
        self.tbOtroDepartamento = QtWidgets.QToolButton(self.frameSuperior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbOtroDepartamento.sizePolicy().hasHeightForWidth())
        self.tbOtroDepartamento.setSizePolicy(sizePolicy)
        self.tbOtroDepartamento.setMinimumSize(QtCore.QSize(27, 27))
        self.tbOtroDepartamento.setMaximumSize(QtCore.QSize(27, 16777215))
        self.tbOtroDepartamento.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tbOtroDepartamento.setObjectName("tbOtroDepartamento")
        self.glCampoRegistrarNombreDep.addWidget(self.tbOtroDepartamento, 1, 2, 1, 1)
        self.vlRegistrarDepYFalla.addLayout(self.glCampoRegistrarNombreDep)
        self.vlCampoRegistrarFallaPresenta = QtWidgets.QVBoxLayout()
        self.vlCampoRegistrarFallaPresenta.setObjectName("vlCampoRegistrarFallaPresenta")
        self.labelFallaPresenta = QtWidgets.QLabel(self.frameSuperior)
        self.labelFallaPresenta.setObjectName("labelFallaPresenta")
        self.vlCampoRegistrarFallaPresenta.addWidget(self.labelFallaPresenta)
        self.inputFallaPresenta = QtWidgets.QLineEdit(self.frameSuperior)
        self.inputFallaPresenta.setObjectName("inputFallaPresenta")
        self.vlCampoRegistrarFallaPresenta.addWidget(self.inputFallaPresenta)
        self.vlRegistrarDepYFalla.addLayout(self.vlCampoRegistrarFallaPresenta)
        self.hlRegistrarServicio.addLayout(self.vlRegistrarDepYFalla)
        self.glCampoRegistrarTecnicosYServicio = QtWidgets.QGridLayout()
        self.glCampoRegistrarTecnicosYServicio.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.glCampoRegistrarTecnicosYServicio.setContentsMargins(-1, -1, 0, -1)
        self.glCampoRegistrarTecnicosYServicio.setObjectName("glCampoRegistrarTecnicosYServicio")
        self.labelNombreTecnico = QtWidgets.QLabel(self.frameSuperior)
        self.labelNombreTecnico.setObjectName("labelNombreTecnico")
        self.glCampoRegistrarTecnicosYServicio.addWidget(self.labelNombreTecnico, 0, 0, 1, 1)
        self.labelServicioPrestado = QtWidgets.QLabel(self.frameSuperior)
        self.labelServicioPrestado.setObjectName("labelServicioPrestado")
        self.glCampoRegistrarTecnicosYServicio.addWidget(self.labelServicioPrestado, 2, 0, 1, 1)
        self.inputServicioPrestado = QtWidgets.QLineEdit(self.frameSuperior)
        self.inputServicioPrestado.setMinimumSize(QtCore.QSize(200, 0))
        self.inputServicioPrestado.setStyleSheet("margin-right: 5px;")
        self.inputServicioPrestado.setObjectName("inputServicioPrestado")
        self.glCampoRegistrarTecnicosYServicio.addWidget(self.inputServicioPrestado, 3, 0, 1, 1)
        self.tbOtroServicioPrestado = QtWidgets.QToolButton(self.frameSuperior)
        self.tbOtroServicioPrestado.setMinimumSize(QtCore.QSize(27, 0))
        self.tbOtroServicioPrestado.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tbOtroServicioPrestado.setObjectName("tbOtroServicioPrestado")
        self.glCampoRegistrarTecnicosYServicio.addWidget(self.tbOtroServicioPrestado, 3, 1, 1, 1)
        self.inputNombreTecnico = QtWidgets.QLineEdit(self.frameSuperior)
        self.inputNombreTecnico.setObjectName("inputNombreTecnico")
        self.glCampoRegistrarTecnicosYServicio.addWidget(self.inputNombreTecnico, 1, 0, 1, 2)
        self.hlRegistrarServicio.addLayout(self.glCampoRegistrarTecnicosYServicio)
        self.vlDescripcion = QtWidgets.QVBoxLayout()
        self.vlDescripcion.setObjectName("vlDescripcion")
        self.labelDescripcion = QtWidgets.QLabel(self.frameSuperior)
        self.labelDescripcion.setObjectName("labelDescripcion")
        self.vlDescripcion.addWidget(self.labelDescripcion)
        self.teDescripcion = QtWidgets.QTextEdit(self.frameSuperior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teDescripcion.sizePolicy().hasHeightForWidth())
        self.teDescripcion.setSizePolicy(sizePolicy)
        self.teDescripcion.setMinimumSize(QtCore.QSize(158, 0))
        self.teDescripcion.setObjectName("teDescripcion")
        self.vlDescripcion.addWidget(self.teDescripcion)
        self.hlRegistrarServicio.addLayout(self.vlDescripcion)
        self.vlObservacionesAdicionales = QtWidgets.QVBoxLayout()
        self.vlObservacionesAdicionales.setObjectName("vlObservacionesAdicionales")
        self.labelObservacionesAdicionales = QtWidgets.QLabel(self.frameSuperior)
        self.labelObservacionesAdicionales.setObjectName("labelObservacionesAdicionales")
        self.vlObservacionesAdicionales.addWidget(self.labelObservacionesAdicionales)
        self.teObservacionesAdicionales = QtWidgets.QTextEdit(self.frameSuperior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teObservacionesAdicionales.sizePolicy().hasHeightForWidth())
        self.teObservacionesAdicionales.setSizePolicy(sizePolicy)
        self.teObservacionesAdicionales.setMinimumSize(QtCore.QSize(0, 0))
        self.teObservacionesAdicionales.setObjectName("teObservacionesAdicionales")
        self.vlObservacionesAdicionales.addWidget(self.teObservacionesAdicionales)
        self.hlRegistrarServicio.addLayout(self.vlObservacionesAdicionales)
        self.vlFechaYCantidad = QtWidgets.QVBoxLayout()
        self.vlFechaYCantidad.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.vlFechaYCantidad.setContentsMargins(-1, 0, -1, 0)
        self.vlFechaYCantidad.setSpacing(0)
        self.vlFechaYCantidad.setObjectName("vlFechaYCantidad")
        self.labelFecha = QtWidgets.QLabel(self.frameSuperior)
        self.labelFecha.setMaximumSize(QtCore.QSize(16777215, 39))
        self.labelFecha.setObjectName("labelFecha")
        self.vlFechaYCantidad.addWidget(self.labelFecha)
        self.deFecha = QtWidgets.QDateEdit(self.frameSuperior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deFecha.sizePolicy().hasHeightForWidth())
        self.deFecha.setSizePolicy(sizePolicy)
        self.deFecha.setMinimumSize(QtCore.QSize(140, 0))
        self.deFecha.setCalendarPopup(True)
        self.deFecha.setObjectName("deFecha")
        self.vlFechaYCantidad.addWidget(self.deFecha)
        self.vlCantidad = QtWidgets.QVBoxLayout()
        self.vlCantidad.setObjectName("vlCantidad")
        self.labelCantidad = QtWidgets.QLabel(self.frameSuperior)
        self.labelCantidad.setObjectName("labelCantidad")
        self.vlCantidad.addWidget(self.labelCantidad)
        self.spCantidad = QtWidgets.QSpinBox(self.frameSuperior)
        self.spCantidad.setMinimumSize(QtCore.QSize(0, 30))
        self.spCantidad.setMinimum(1)
        self.spCantidad.setMaximum(9999999)
        self.spCantidad.setObjectName("spCantidad")
        self.vlCantidad.addWidget(self.spCantidad)
        self.vlFechaYCantidad.addLayout(self.vlCantidad)
        self.hlRegistrarServicio.addLayout(self.vlFechaYCantidad)
        self.vlManualUsuarioYRegistrar = QtWidgets.QVBoxLayout()
        self.vlManualUsuarioYRegistrar.setSpacing(68)
        self.vlManualUsuarioYRegistrar.setObjectName("vlManualUsuarioYRegistrar")
        self.botonManualUsuarioSeccionApp = QtWidgets.QPushButton(self.frameSuperior)
        self.botonManualUsuarioSeccionApp.setMinimumSize(QtCore.QSize(40, 40))
        self.botonManualUsuarioSeccionApp.setMaximumSize(QtCore.QSize(40, 40))
        self.botonManualUsuarioSeccionApp.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonManualUsuarioSeccionApp.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.botonManualUsuarioSeccionApp.setAutoFillBackground(False)
        self.botonManualUsuarioSeccionApp.setStyleSheet("")
        self.botonManualUsuarioSeccionApp.setText("")
        self.botonManualUsuarioSeccionApp.setObjectName("botonManualUsuarioSeccionApp")
        self.vlManualUsuarioYRegistrar.addWidget(self.botonManualUsuarioSeccionApp)
        self.botonRegistrar = QtWidgets.QPushButton(self.frameSuperior)
        self.botonRegistrar.setMinimumSize(QtCore.QSize(145, 32))
        self.botonRegistrar.setMaximumSize(QtCore.QSize(175, 16777215))
        self.botonRegistrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonRegistrar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonRegistrar.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/iconos/iconos/icono-agregar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonRegistrar.setIcon(icon2)
        self.botonRegistrar.setIconSize(QtCore.QSize(20, 20))
        self.botonRegistrar.setObjectName("botonRegistrar")
        self.vlManualUsuarioYRegistrar.addWidget(self.botonRegistrar)
        self.hlRegistrarServicio.addLayout(self.vlManualUsuarioYRegistrar)
        self.hlRegistrarServicio.setStretch(0, 2)
        self.hlRegistrarServicio.setStretch(1, 2)
        self.hlRegistrarServicio.setStretch(2, 2)
        self.hlRegistrarServicio.setStretch(3, 2)
        self.hlRegistrarServicio.setStretch(4, 1)
        self.hlRegistrarServicio.setStretch(5, 1)
        self.vlRegistroYFiltroServicio.addLayout(self.hlRegistrarServicio)
        self.lineaSeparadoraSeccionApp = QtWidgets.QFrame(self.frameSuperior)
        self.lineaSeparadoraSeccionApp.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineaSeparadoraSeccionApp.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineaSeparadoraSeccionApp.setObjectName("lineaSeparadoraSeccionApp")
        self.vlRegistroYFiltroServicio.addWidget(self.lineaSeparadoraSeccionApp)
        self.vlFiltroServicio = QtWidgets.QVBoxLayout()
        self.vlFiltroServicio.setObjectName("vlFiltroServicio")
        self.vlSeccionFiltrarServicios = QtWidgets.QVBoxLayout()
        self.vlSeccionFiltrarServicios.setObjectName("vlSeccionFiltrarServicios")
        self.hlLabelsFiltroServicios = QtWidgets.QHBoxLayout()
        self.hlLabelsFiltroServicios.setContentsMargins(-1, -1, 185, -1)
        self.hlLabelsFiltroServicios.setSpacing(6)
        self.hlLabelsFiltroServicios.setObjectName("hlLabelsFiltroServicios")
        self.labelFiltroFecha = QtWidgets.QLabel(self.frameSuperior)
        self.labelFiltroFecha.setMaximumSize(QtCore.QSize(295, 16777215))
        self.labelFiltroFecha.setObjectName("labelFiltroFecha")
        self.hlLabelsFiltroServicios.addWidget(self.labelFiltroFecha)
        self.labelFiltroDepartamento = QtWidgets.QLabel(self.frameSuperior)
        self.labelFiltroDepartamento.setObjectName("labelFiltroDepartamento")
        self.hlLabelsFiltroServicios.addWidget(self.labelFiltroDepartamento)
        self.labelFiltroServicioPrestado = QtWidgets.QLabel(self.frameSuperior)
        self.labelFiltroServicioPrestado.setObjectName("labelFiltroServicioPrestado")
        self.hlLabelsFiltroServicios.addWidget(self.labelFiltroServicioPrestado)
        self.vlSeccionFiltrarServicios.addLayout(self.hlLabelsFiltroServicios)
        self.hlElementosFiltroServicio = QtWidgets.QHBoxLayout()
        self.hlElementosFiltroServicio.setSpacing(7)
        self.hlElementosFiltroServicio.setObjectName("hlElementosFiltroServicio")
        self.deFiltroFecha = QtWidgets.QDateEdit(self.frameSuperior)
        self.deFiltroFecha.setMaximumSize(QtCore.QSize(295, 16777215))
        self.deFiltroFecha.setReadOnly(False)
        self.deFiltroFecha.setKeyboardTracking(True)
        self.deFiltroFecha.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.deFiltroFecha.setCalendarPopup(True)
        self.deFiltroFecha.setTimeSpec(QtCore.Qt.LocalTime)
        self.deFiltroFecha.setObjectName("deFiltroFecha")
        self.hlElementosFiltroServicio.addWidget(self.deFiltroFecha)
        self.inputFiltroDepartamento = QtWidgets.QLineEdit(self.frameSuperior)
        self.inputFiltroDepartamento.setObjectName("inputFiltroDepartamento")
        self.hlElementosFiltroServicio.addWidget(self.inputFiltroDepartamento)
        self.inputFiltroServicioPrestado = QtWidgets.QLineEdit(self.frameSuperior)
        self.inputFiltroServicioPrestado.setObjectName("inputFiltroServicioPrestado")
        self.hlElementosFiltroServicio.addWidget(self.inputFiltroServicioPrestado)
        self.botonBuscarServicios = QtWidgets.QPushButton(self.frameSuperior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonBuscarServicios.sizePolicy().hasHeightForWidth())
        self.botonBuscarServicios.setSizePolicy(sizePolicy)
        self.botonBuscarServicios.setMinimumSize(QtCore.QSize(140, 32))
        self.botonBuscarServicios.setMaximumSize(QtCore.QSize(140, 26))
        self.botonBuscarServicios.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/iconos/iconos/icono-buscar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonBuscarServicios.setIcon(icon3)
        self.botonBuscarServicios.setObjectName("botonBuscarServicios")
        self.hlElementosFiltroServicio.addWidget(self.botonBuscarServicios)
        self.botonRefrescarApp = QtWidgets.QPushButton(self.frameSuperior)
        self.botonRefrescarApp.setMinimumSize(QtCore.QSize(32, 32))
        self.botonRefrescarApp.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonRefrescarApp.setStyleSheet("")
        self.botonRefrescarApp.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/iconos/iconos/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonRefrescarApp.setIcon(icon4)
        self.botonRefrescarApp.setObjectName("botonRefrescarApp")
        self.hlElementosFiltroServicio.addWidget(self.botonRefrescarApp)
        self.hlElementosFiltroServicio.setStretch(0, 1)
        self.hlElementosFiltroServicio.setStretch(1, 1)
        self.hlElementosFiltroServicio.setStretch(2, 1)
        self.vlSeccionFiltrarServicios.addLayout(self.hlElementosFiltroServicio)
        self.vlFiltroServicio.addLayout(self.vlSeccionFiltrarServicios)
        self.labelErrorFiltro = QtWidgets.QLabel(self.frameSuperior)
        self.labelErrorFiltro.setText("")
        self.labelErrorFiltro.setAlignment(QtCore.Qt.AlignCenter)
        self.labelErrorFiltro.setObjectName("labelErrorFiltro")
        self.vlFiltroServicio.addWidget(self.labelErrorFiltro)
        self.vlRegistroYFiltroServicio.addLayout(self.vlFiltroServicio)
        self.horizontalLayout_2.addLayout(self.vlRegistroYFiltroServicio)
        self.verticalLayout_4.addWidget(self.frameSuperior)
        self.frameRegistros = QtWidgets.QFrame(self.frameApp)
        self.frameRegistros.setMinimumSize(QtCore.QSize(0, 100))
        self.frameRegistros.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRegistros.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRegistros.setObjectName("frameRegistros")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frameRegistros)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tvRegistros = QtWidgets.QTableView(self.frameRegistros)
        self.tvRegistros.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tvRegistros.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tvRegistros.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tvRegistros.setShowGrid(True)
        self.tvRegistros.setGridStyle(QtCore.Qt.SolidLine)
        self.tvRegistros.setCornerButtonEnabled(True)
        self.tvRegistros.setObjectName("tvRegistros")
        self.tvRegistros.verticalHeader().setVisible(False)
        self.verticalLayout_5.addWidget(self.tvRegistros)
        self.verticalLayout_4.addWidget(self.frameRegistros)
        self.frameInferior = QtWidgets.QFrame(self.frameApp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameInferior.sizePolicy().hasHeightForWidth())
        self.frameInferior.setSizePolicy(sizePolicy)
        self.frameInferior.setMinimumSize(QtCore.QSize(1232, 70))
        self.frameInferior.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frameInferior.setStyleSheet("")
        self.frameInferior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameInferior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameInferior.setObjectName("frameInferior")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameInferior)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hlBotonesInferiores = QtWidgets.QHBoxLayout()
        self.hlBotonesInferiores.setSpacing(30)
        self.hlBotonesInferiores.setObjectName("hlBotonesInferiores")
        self.botonCrearUsuario = QtWidgets.QPushButton(self.frameInferior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonCrearUsuario.sizePolicy().hasHeightForWidth())
        self.botonCrearUsuario.setSizePolicy(sizePolicy)
        self.botonCrearUsuario.setMinimumSize(QtCore.QSize(170, 0))
        self.botonCrearUsuario.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonCrearUsuario.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/iconos/iconos/icono-usuarios.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonCrearUsuario.setIcon(icon5)
        self.botonCrearUsuario.setIconSize(QtCore.QSize(24, 24))
        self.botonCrearUsuario.setObjectName("botonCrearUsuario")
        self.hlBotonesInferiores.addWidget(self.botonCrearUsuario)
        self.botonCrearRespaldo = QtWidgets.QPushButton(self.frameInferior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonCrearRespaldo.sizePolicy().hasHeightForWidth())
        self.botonCrearRespaldo.setSizePolicy(sizePolicy)
        self.botonCrearRespaldo.setMinimumSize(QtCore.QSize(170, 0))
        self.botonCrearRespaldo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/iconos/iconos/icono-crear-respaldo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonCrearRespaldo.setIcon(icon6)
        self.botonCrearRespaldo.setIconSize(QtCore.QSize(24, 24))
        self.botonCrearRespaldo.setObjectName("botonCrearRespaldo")
        self.hlBotonesInferiores.addWidget(self.botonCrearRespaldo)
        self.botonImportarRespaldo = QtWidgets.QPushButton(self.frameInferior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonImportarRespaldo.sizePolicy().hasHeightForWidth())
        self.botonImportarRespaldo.setSizePolicy(sizePolicy)
        self.botonImportarRespaldo.setMinimumSize(QtCore.QSize(170, 0))
        self.botonImportarRespaldo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/iconos/iconos/icono-importar-respaldo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonImportarRespaldo.setIcon(icon7)
        self.botonImportarRespaldo.setIconSize(QtCore.QSize(24, 24))
        self.botonImportarRespaldo.setObjectName("botonImportarRespaldo")
        self.hlBotonesInferiores.addWidget(self.botonImportarRespaldo)
        self.botonGenerarReporte = QtWidgets.QPushButton(self.frameInferior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonGenerarReporte.sizePolicy().hasHeightForWidth())
        self.botonGenerarReporte.setSizePolicy(sizePolicy)
        self.botonGenerarReporte.setMinimumSize(QtCore.QSize(170, 0))
        self.botonGenerarReporte.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/iconos/iconos/icono-generar-reporte.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonGenerarReporte.setIcon(icon8)
        self.botonGenerarReporte.setIconSize(QtCore.QSize(24, 24))
        self.botonGenerarReporte.setObjectName("botonGenerarReporte")
        self.hlBotonesInferiores.addWidget(self.botonGenerarReporte)
        self.botonCerrarSesion = QtWidgets.QPushButton(self.frameInferior)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonCerrarSesion.sizePolicy().hasHeightForWidth())
        self.botonCerrarSesion.setSizePolicy(sizePolicy)
        self.botonCerrarSesion.setMinimumSize(QtCore.QSize(170, 0))
        self.botonCerrarSesion.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonCerrarSesion.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonCerrarSesion.setStyleSheet("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/iconos/iconos/icono-cerrar-sesion.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonCerrarSesion.setIcon(icon9)
        self.botonCerrarSesion.setObjectName("botonCerrarSesion")
        self.hlBotonesInferiores.addWidget(self.botonCerrarSesion)
        self.verticalLayout_2.addLayout(self.hlBotonesInferiores)
        self.verticalLayout_4.addWidget(self.frameInferior, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.frameApp)
        self.ventanas.addWidget(self.paginaApp)
        self.paginaCrearUsuario = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paginaCrearUsuario.sizePolicy().hasHeightForWidth())
        self.paginaCrearUsuario.setSizePolicy(sizePolicy)
        self.paginaCrearUsuario.setObjectName("paginaCrearUsuario")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.paginaCrearUsuario)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frameGeneralUsuarios = QtWidgets.QFrame(self.paginaCrearUsuario)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameGeneralUsuarios.sizePolicy().hasHeightForWidth())
        self.frameGeneralUsuarios.setSizePolicy(sizePolicy)
        self.frameGeneralUsuarios.setMinimumSize(QtCore.QSize(1252, 685))
        self.frameGeneralUsuarios.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGeneralUsuarios.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGeneralUsuarios.setObjectName("frameGeneralUsuarios")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frameGeneralUsuarios)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frameSeccionRegistrarUsuario = QtWidgets.QFrame(self.frameGeneralUsuarios)
        self.frameSeccionRegistrarUsuario.setMinimumSize(QtCore.QSize(876, 209))
        self.frameSeccionRegistrarUsuario.setMaximumSize(QtCore.QSize(16777215, 209))
        self.frameSeccionRegistrarUsuario.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSeccionRegistrarUsuario.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSeccionRegistrarUsuario.setObjectName("frameSeccionRegistrarUsuario")
        self.botonRegistrarUsuario = QtWidgets.QPushButton(self.frameSeccionRegistrarUsuario)
        self.botonRegistrarUsuario.setGeometry(QtCore.QRect(880, 120, 141, 32))
        self.botonRegistrarUsuario.setMinimumSize(QtCore.QSize(0, 32))
        self.botonRegistrarUsuario.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonRegistrarUsuario.setIcon(icon2)
        self.botonRegistrarUsuario.setIconSize(QtCore.QSize(20, 20))
        self.botonRegistrarUsuario.setObjectName("botonRegistrarUsuario")
        self.labelTituloRegistrarUsuario = QtWidgets.QLabel(self.frameSeccionRegistrarUsuario)
        self.labelTituloRegistrarUsuario.setGeometry(QtCore.QRect(494, 10, 231, 20))
        self.labelTituloRegistrarUsuario.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTituloRegistrarUsuario.setObjectName("labelTituloRegistrarUsuario")
        self.layoutWidget1 = QtWidgets.QWidget(self.frameSeccionRegistrarUsuario)
        self.layoutWidget1.setGeometry(QtCore.QRect(370, 60, 481, 97))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.glCamposRegistrarUsuario = QtWidgets.QGridLayout(self.layoutWidget1)
        self.glCamposRegistrarUsuario.setContentsMargins(0, 0, 0, 0)
        self.glCamposRegistrarUsuario.setObjectName("glCamposRegistrarUsuario")
        self.labelRegistrarNombreUsuario = QtWidgets.QLabel(self.layoutWidget1)
        self.labelRegistrarNombreUsuario.setObjectName("labelRegistrarNombreUsuario")
        self.glCamposRegistrarUsuario.addWidget(self.labelRegistrarNombreUsuario, 0, 0, 1, 1)
        self.inputRegistrarNombreUsuario = QtWidgets.QLineEdit(self.layoutWidget1)
        self.inputRegistrarNombreUsuario.setObjectName("inputRegistrarNombreUsuario")
        self.glCamposRegistrarUsuario.addWidget(self.inputRegistrarNombreUsuario, 0, 1, 1, 1)
        self.labelRegistrarRol = QtWidgets.QLabel(self.layoutWidget1)
        self.labelRegistrarRol.setObjectName("labelRegistrarRol")
        self.glCamposRegistrarUsuario.addWidget(self.labelRegistrarRol, 1, 0, 1, 1)
        self.labelRegistrarClave = QtWidgets.QLabel(self.layoutWidget1)
        self.labelRegistrarClave.setObjectName("labelRegistrarClave")
        self.glCamposRegistrarUsuario.addWidget(self.labelRegistrarClave, 2, 0, 1, 1)
        self.inputRegistrarClaveUsuario = QtWidgets.QLineEdit(self.layoutWidget1)
        self.inputRegistrarClaveUsuario.setObjectName("inputRegistrarClaveUsuario")
        self.glCamposRegistrarUsuario.addWidget(self.inputRegistrarClaveUsuario, 2, 1, 1, 1)
        self.cbRolesRegistrarUsuario = QtWidgets.QComboBox(self.layoutWidget1)
        self.cbRolesRegistrarUsuario.setObjectName("cbRolesRegistrarUsuario")
        self.cbRolesRegistrarUsuario.addItem("")
        self.cbRolesRegistrarUsuario.addItem("")
        self.glCamposRegistrarUsuario.addWidget(self.cbRolesRegistrarUsuario, 1, 1, 1, 1)
        self.botonRefrescarUsuarios = QtWidgets.QPushButton(self.frameSeccionRegistrarUsuario)
        self.botonRefrescarUsuarios.setGeometry(QtCore.QRect(1040, 120, 31, 28))
        self.botonRefrescarUsuarios.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonRefrescarUsuarios.setStyleSheet("")
        self.botonRefrescarUsuarios.setText("")
        self.botonRefrescarUsuarios.setIcon(icon4)
        self.botonRefrescarUsuarios.setObjectName("botonRefrescarUsuarios")
        self.lineaSeparadoraSeccionUsuarios = QtWidgets.QFrame(self.frameSeccionRegistrarUsuario)
        self.lineaSeparadoraSeccionUsuarios.setGeometry(QtCore.QRect(0, 170, 1221, 21))
        self.lineaSeparadoraSeccionUsuarios.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineaSeparadoraSeccionUsuarios.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineaSeparadoraSeccionUsuarios.setObjectName("lineaSeparadoraSeccionUsuarios")
        self.botonManualUsuarioSeccionUsuarios = QtWidgets.QPushButton(self.frameSeccionRegistrarUsuario)
        self.botonManualUsuarioSeccionUsuarios.setGeometry(QtCore.QRect(1180, 0, 40, 40))
        self.botonManualUsuarioSeccionUsuarios.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonManualUsuarioSeccionUsuarios.setStyleSheet("")
        self.botonManualUsuarioSeccionUsuarios.setText("")
        self.botonManualUsuarioSeccionUsuarios.setObjectName("botonManualUsuarioSeccionUsuarios")
        self.verticalLayout_12.addWidget(self.frameSeccionRegistrarUsuario)
        self.frameListaUsuarios = QtWidgets.QFrame(self.frameGeneralUsuarios)
        self.frameListaUsuarios.setMinimumSize(QtCore.QSize(852, 0))
        self.frameListaUsuarios.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameListaUsuarios.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameListaUsuarios.setObjectName("frameListaUsuarios")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frameListaUsuarios)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.tvUsuarios = QtWidgets.QTableView(self.frameListaUsuarios)
        self.tvUsuarios.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tvUsuarios.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tvUsuarios.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tvUsuarios.setObjectName("tvUsuarios")
        self.tvUsuarios.verticalHeader().setVisible(False)
        self.verticalLayout_13.addWidget(self.tvUsuarios)
        self.verticalLayout_12.addWidget(self.frameListaUsuarios)
        self.frameInferiorSeccionUsuarios = QtWidgets.QFrame(self.frameGeneralUsuarios)
        self.frameInferiorSeccionUsuarios.setMinimumSize(QtCore.QSize(876, 80))
        self.frameInferiorSeccionUsuarios.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frameInferiorSeccionUsuarios.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameInferiorSeccionUsuarios.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameInferiorSeccionUsuarios.setObjectName("frameInferiorSeccionUsuarios")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frameInferiorSeccionUsuarios)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.botonRegresarSeccionUsuarios = QtWidgets.QPushButton(self.frameInferiorSeccionUsuarios)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonRegresarSeccionUsuarios.sizePolicy().hasHeightForWidth())
        self.botonRegresarSeccionUsuarios.setSizePolicy(sizePolicy)
        self.botonRegresarSeccionUsuarios.setMinimumSize(QtCore.QSize(200, 35))
        self.botonRegresarSeccionUsuarios.setMaximumSize(QtCore.QSize(200, 35))
        self.botonRegresarSeccionUsuarios.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/iconos/iconos/icono-regresar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonRegresarSeccionUsuarios.setIcon(icon10)
        self.botonRegresarSeccionUsuarios.setIconSize(QtCore.QSize(24, 24))
        self.botonRegresarSeccionUsuarios.setObjectName("botonRegresarSeccionUsuarios")
        self.verticalLayout_21.addWidget(self.botonRegresarSeccionUsuarios, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_12.addWidget(self.frameInferiorSeccionUsuarios)
        self.verticalLayout_8.addWidget(self.frameGeneralUsuarios, 0, QtCore.Qt.AlignHCenter)
        self.ventanas.addWidget(self.paginaCrearUsuario)
        self.paginaDepartamentos = QtWidgets.QWidget()
        self.paginaDepartamentos.setObjectName("paginaDepartamentos")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.paginaDepartamentos)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frameGeneralDepartamentos = QtWidgets.QFrame(self.paginaDepartamentos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameGeneralDepartamentos.sizePolicy().hasHeightForWidth())
        self.frameGeneralDepartamentos.setSizePolicy(sizePolicy)
        self.frameGeneralDepartamentos.setMinimumSize(QtCore.QSize(1252, 685))
        self.frameGeneralDepartamentos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGeneralDepartamentos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGeneralDepartamentos.setObjectName("frameGeneralDepartamentos")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frameGeneralDepartamentos)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frameSeccionRegistrarDepartamento = QtWidgets.QFrame(self.frameGeneralDepartamentos)
        self.frameSeccionRegistrarDepartamento.setMinimumSize(QtCore.QSize(0, 229))
        self.frameSeccionRegistrarDepartamento.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSeccionRegistrarDepartamento.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSeccionRegistrarDepartamento.setObjectName("frameSeccionRegistrarDepartamento")
        self.labelTituloRegistrarDepartamento = QtWidgets.QLabel(self.frameSeccionRegistrarDepartamento)
        self.labelTituloRegistrarDepartamento.setGeometry(QtCore.QRect(290, 10, 631, 31))
        self.labelTituloRegistrarDepartamento.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTituloRegistrarDepartamento.setObjectName("labelTituloRegistrarDepartamento")
        self.lineaSeparadoraSeccionDepartamento = QtWidgets.QFrame(self.frameSeccionRegistrarDepartamento)
        self.lineaSeparadoraSeccionDepartamento.setGeometry(QtCore.QRect(0, 110, 1231, 21))
        self.lineaSeparadoraSeccionDepartamento.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineaSeparadoraSeccionDepartamento.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineaSeparadoraSeccionDepartamento.setObjectName("lineaSeparadoraSeccionDepartamento")
        self.layoutWidget2 = QtWidgets.QWidget(self.frameSeccionRegistrarDepartamento)
        self.layoutWidget2.setGeometry(QtCore.QRect(300, 70, 631, 34))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.hlSeccionRegistrarDepartamento = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.hlSeccionRegistrarDepartamento.setContentsMargins(0, 0, 0, 0)
        self.hlSeccionRegistrarDepartamento.setObjectName("hlSeccionRegistrarDepartamento")
        self.hlCamposRegistrarDepartamento = QtWidgets.QHBoxLayout()
        self.hlCamposRegistrarDepartamento.setObjectName("hlCamposRegistrarDepartamento")
        self.labelNombreDepartamento = QtWidgets.QLabel(self.layoutWidget2)
        self.labelNombreDepartamento.setObjectName("labelNombreDepartamento")
        self.hlCamposRegistrarDepartamento.addWidget(self.labelNombreDepartamento)
        self.inputNombreDepartamento = QtWidgets.QLineEdit(self.layoutWidget2)
        self.inputNombreDepartamento.setObjectName("inputNombreDepartamento")
        self.hlCamposRegistrarDepartamento.addWidget(self.inputNombreDepartamento)
        self.hlSeccionRegistrarDepartamento.addLayout(self.hlCamposRegistrarDepartamento)
        self.botonRegistrarDepartamento = QtWidgets.QPushButton(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonRegistrarDepartamento.sizePolicy().hasHeightForWidth())
        self.botonRegistrarDepartamento.setSizePolicy(sizePolicy)
        self.botonRegistrarDepartamento.setMinimumSize(QtCore.QSize(0, 32))
        self.botonRegistrarDepartamento.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonRegistrarDepartamento.setIcon(icon2)
        self.botonRegistrarDepartamento.setObjectName("botonRegistrarDepartamento")
        self.hlSeccionRegistrarDepartamento.addWidget(self.botonRegistrarDepartamento)
        self.hlSeccionRegistrarDepartamento.setStretch(0, 3)
        self.hlSeccionRegistrarDepartamento.setStretch(1, 1)
        self.labelFiltroSeccionDepartamento = QtWidgets.QLabel(self.frameSeccionRegistrarDepartamento)
        self.labelFiltroSeccionDepartamento.setGeometry(QtCore.QRect(320, 200, 591, 31))
        self.labelFiltroSeccionDepartamento.setText("")
        self.labelFiltroSeccionDepartamento.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFiltroSeccionDepartamento.setObjectName("labelFiltroSeccionDepartamento")
        self.botonManualUsuarioSeccionDepartamentos = QtWidgets.QPushButton(self.frameSeccionRegistrarDepartamento)
        self.botonManualUsuarioSeccionDepartamentos.setGeometry(QtCore.QRect(1180, 10, 40, 40))
        self.botonManualUsuarioSeccionDepartamentos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonManualUsuarioSeccionDepartamentos.setStyleSheet("")
        self.botonManualUsuarioSeccionDepartamentos.setText("")
        self.botonManualUsuarioSeccionDepartamentos.setObjectName("botonManualUsuarioSeccionDepartamentos")
        self.botonBuscarDepartamento = QtWidgets.QPushButton(self.frameSeccionRegistrarDepartamento)
        self.botonBuscarDepartamento.setGeometry(QtCore.QRect(690, 170, 155, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonBuscarDepartamento.sizePolicy().hasHeightForWidth())
        self.botonBuscarDepartamento.setSizePolicy(sizePolicy)
        self.botonBuscarDepartamento.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonBuscarDepartamento.setIcon(icon3)
        self.botonBuscarDepartamento.setIconSize(QtCore.QSize(20, 20))
        self.botonBuscarDepartamento.setObjectName("botonBuscarDepartamento")
        self.botonRefrescarDepartamentos = QtWidgets.QPushButton(self.frameSeccionRegistrarDepartamento)
        self.botonRefrescarDepartamentos.setGeometry(QtCore.QRect(860, 170, 26, 24))
        self.botonRefrescarDepartamentos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonRefrescarDepartamentos.setStyleSheet("")
        self.botonRefrescarDepartamentos.setText("")
        self.botonRefrescarDepartamentos.setIcon(icon4)
        self.botonRefrescarDepartamentos.setObjectName("botonRefrescarDepartamentos")
        self.layoutWidget3 = QtWidgets.QWidget(self.frameSeccionRegistrarDepartamento)
        self.layoutWidget3.setGeometry(QtCore.QRect(300, 140, 371, 53))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.labelBuscarDepartamento = QtWidgets.QLabel(self.layoutWidget3)
        self.labelBuscarDepartamento.setObjectName("labelBuscarDepartamento")
        self.verticalLayout_20.addWidget(self.labelBuscarDepartamento)
        self.inputBuscarDepartamento = QtWidgets.QLineEdit(self.layoutWidget3)
        self.inputBuscarDepartamento.setObjectName("inputBuscarDepartamento")
        self.verticalLayout_20.addWidget(self.inputBuscarDepartamento)
        self.verticalLayout_14.addWidget(self.frameSeccionRegistrarDepartamento)
        self.frameListaDepartamentos = QtWidgets.QFrame(self.frameGeneralDepartamentos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameListaDepartamentos.sizePolicy().hasHeightForWidth())
        self.frameListaDepartamentos.setSizePolicy(sizePolicy)
        self.frameListaDepartamentos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameListaDepartamentos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameListaDepartamentos.setObjectName("frameListaDepartamentos")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frameListaDepartamentos)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tvDepartamentos = QtWidgets.QTableView(self.frameListaDepartamentos)
        self.tvDepartamentos.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tvDepartamentos.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tvDepartamentos.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tvDepartamentos.setObjectName("tvDepartamentos")
        self.tvDepartamentos.verticalHeader().setVisible(False)
        self.verticalLayout_7.addWidget(self.tvDepartamentos)
        self.verticalLayout_14.addWidget(self.frameListaDepartamentos)
        self.frameInferiorSeccionDepartamentos = QtWidgets.QFrame(self.frameGeneralDepartamentos)
        self.frameInferiorSeccionDepartamentos.setMinimumSize(QtCore.QSize(1234, 51))
        self.frameInferiorSeccionDepartamentos.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frameInferiorSeccionDepartamentos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameInferiorSeccionDepartamentos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameInferiorSeccionDepartamentos.setObjectName("frameInferiorSeccionDepartamentos")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frameInferiorSeccionDepartamentos)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.botonRegresarSeccionDepartamentos = QtWidgets.QPushButton(self.frameInferiorSeccionDepartamentos)
        self.botonRegresarSeccionDepartamentos.setMinimumSize(QtCore.QSize(200, 35))
        self.botonRegresarSeccionDepartamentos.setMaximumSize(QtCore.QSize(200, 35))
        self.botonRegresarSeccionDepartamentos.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonRegresarSeccionDepartamentos.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botonRegresarSeccionDepartamentos.setIcon(icon10)
        self.botonRegresarSeccionDepartamentos.setIconSize(QtCore.QSize(24, 24))
        self.botonRegresarSeccionDepartamentos.setObjectName("botonRegresarSeccionDepartamentos")
        self.verticalLayout_22.addWidget(self.botonRegresarSeccionDepartamentos, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_14.addWidget(self.frameInferiorSeccionDepartamentos, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_6.addWidget(self.frameGeneralDepartamentos, 0, QtCore.Qt.AlignHCenter)
        self.ventanas.addWidget(self.paginaDepartamentos)
        self.paginaTiposServicio = QtWidgets.QWidget()
        self.paginaTiposServicio.setObjectName("paginaTiposServicio")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.paginaTiposServicio)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frameGeneralTipoServicio = QtWidgets.QFrame(self.paginaTiposServicio)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameGeneralTipoServicio.sizePolicy().hasHeightForWidth())
        self.frameGeneralTipoServicio.setSizePolicy(sizePolicy)
        self.frameGeneralTipoServicio.setMinimumSize(QtCore.QSize(1252, 685))
        self.frameGeneralTipoServicio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGeneralTipoServicio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGeneralTipoServicio.setObjectName("frameGeneralTipoServicio")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frameGeneralTipoServicio)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frameSuperiorTipoServicio = QtWidgets.QFrame(self.frameGeneralTipoServicio)
        self.frameSuperiorTipoServicio.setMinimumSize(QtCore.QSize(876, 229))
        self.frameSuperiorTipoServicio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSuperiorTipoServicio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSuperiorTipoServicio.setObjectName("frameSuperiorTipoServicio")
        self.labelTituloRegistrarTipoServicio = QtWidgets.QLabel(self.frameSuperiorTipoServicio)
        self.labelTituloRegistrarTipoServicio.setGeometry(QtCore.QRect(330, 10, 591, 41))
        self.labelTituloRegistrarTipoServicio.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTituloRegistrarTipoServicio.setObjectName("labelTituloRegistrarTipoServicio")
        self.lineaSeparadoraSeccionTipoServicio = QtWidgets.QFrame(self.frameSuperiorTipoServicio)
        self.lineaSeparadoraSeccionTipoServicio.setGeometry(QtCore.QRect(0, 120, 1231, 20))
        self.lineaSeparadoraSeccionTipoServicio.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineaSeparadoraSeccionTipoServicio.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineaSeparadoraSeccionTipoServicio.setObjectName("lineaSeparadoraSeccionTipoServicio")
        self.labelFiltroSeccionTipoServicio = QtWidgets.QLabel(self.frameSuperiorTipoServicio)
        self.labelFiltroSeccionTipoServicio.setGeometry(QtCore.QRect(260, 200, 591, 20))
        self.labelFiltroSeccionTipoServicio.setText("")
        self.labelFiltroSeccionTipoServicio.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFiltroSeccionTipoServicio.setObjectName("labelFiltroSeccionTipoServicio")
        self.botonRefrescarTiposServicio = QtWidgets.QPushButton(self.frameSuperiorTipoServicio)
        self.botonRefrescarTiposServicio.setGeometry(QtCore.QRect(1070, 170, 26, 24))
        self.botonRefrescarTiposServicio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonRefrescarTiposServicio.setStyleSheet("")
        self.botonRefrescarTiposServicio.setText("")
        self.botonRefrescarTiposServicio.setIcon(icon4)
        self.botonRefrescarTiposServicio.setObjectName("botonRefrescarTiposServicio")
        self.botonManualUsuarioSeccionTipoServicio = QtWidgets.QPushButton(self.frameSuperiorTipoServicio)
        self.botonManualUsuarioSeccionTipoServicio.setGeometry(QtCore.QRect(1180, 10, 40, 40))
        self.botonManualUsuarioSeccionTipoServicio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonManualUsuarioSeccionTipoServicio.setStyleSheet("")
        self.botonManualUsuarioSeccionTipoServicio.setText("")
        self.botonManualUsuarioSeccionTipoServicio.setObjectName("botonManualUsuarioSeccionTipoServicio")
        self.botonBuscarTipoServicio = QtWidgets.QPushButton(self.frameSuperiorTipoServicio)
        self.botonBuscarTipoServicio.setGeometry(QtCore.QRect(910, 170, 148, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonBuscarTipoServicio.sizePolicy().hasHeightForWidth())
        self.botonBuscarTipoServicio.setSizePolicy(sizePolicy)
        self.botonBuscarTipoServicio.setMinimumSize(QtCore.QSize(148, 30))
        self.botonBuscarTipoServicio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonBuscarTipoServicio.setIcon(icon3)
        self.botonBuscarTipoServicio.setObjectName("botonBuscarTipoServicio")
        self.layoutWidget4 = QtWidgets.QWidget(self.frameSuperiorTipoServicio)
        self.layoutWidget4.setGeometry(QtCore.QRect(200, 140, 701, 55))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.hlFiltroTipoServicio = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.hlFiltroTipoServicio.setContentsMargins(0, 0, 0, 0)
        self.hlFiltroTipoServicio.setSpacing(7)
        self.hlFiltroTipoServicio.setObjectName("hlFiltroTipoServicio")
        self.vlFiltroTipo = QtWidgets.QVBoxLayout()
        self.vlFiltroTipo.setObjectName("vlFiltroTipo")
        self.labelFiltroTipoServicio = QtWidgets.QLabel(self.layoutWidget4)
        self.labelFiltroTipoServicio.setObjectName("labelFiltroTipoServicio")
        self.vlFiltroTipo.addWidget(self.labelFiltroTipoServicio)
        self.inputFiltroTipoServicio = QtWidgets.QLineEdit(self.layoutWidget4)
        self.inputFiltroTipoServicio.setObjectName("inputFiltroTipoServicio")
        self.vlFiltroTipo.addWidget(self.inputFiltroTipoServicio)
        self.hlFiltroTipoServicio.addLayout(self.vlFiltroTipo)
        self.vlFiltroCategoria = QtWidgets.QVBoxLayout()
        self.vlFiltroCategoria.setObjectName("vlFiltroCategoria")
        self.labelFiltroCategoria = QtWidgets.QLabel(self.layoutWidget4)
        self.labelFiltroCategoria.setObjectName("labelFiltroCategoria")
        self.vlFiltroCategoria.addWidget(self.labelFiltroCategoria)
        self.inputFiltroCategoria = QtWidgets.QLineEdit(self.layoutWidget4)
        self.inputFiltroCategoria.setObjectName("inputFiltroCategoria")
        self.vlFiltroCategoria.addWidget(self.inputFiltroCategoria)
        self.hlFiltroTipoServicio.addLayout(self.vlFiltroCategoria)
        self.widget = QtWidgets.QWidget(self.frameSuperiorTipoServicio)
        self.widget.setGeometry(QtCore.QRect(20, 80, 1141, 34))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.hRegistrarCamposTipoServicio = QtWidgets.QHBoxLayout()
        self.hRegistrarCamposTipoServicio.setSpacing(10)
        self.hRegistrarCamposTipoServicio.setObjectName("hRegistrarCamposTipoServicio")
        self.hlRegistrarNombreTipoServicio = QtWidgets.QHBoxLayout()
        self.hlRegistrarNombreTipoServicio.setObjectName("hlRegistrarNombreTipoServicio")
        self.labelCampoTipoServicio = QtWidgets.QLabel(self.widget)
        self.labelCampoTipoServicio.setObjectName("labelCampoTipoServicio")
        self.hlRegistrarNombreTipoServicio.addWidget(self.labelCampoTipoServicio)
        self.inputRegistrarTipoServicio = QtWidgets.QLineEdit(self.widget)
        self.inputRegistrarTipoServicio.setObjectName("inputRegistrarTipoServicio")
        self.hlRegistrarNombreTipoServicio.addWidget(self.inputRegistrarTipoServicio)
        self.hRegistrarCamposTipoServicio.addLayout(self.hlRegistrarNombreTipoServicio)
        self.hlRegistrarNombreCategoria = QtWidgets.QHBoxLayout()
        self.hlRegistrarNombreCategoria.setObjectName("hlRegistrarNombreCategoria")
        self.labelCampoCategoria = QtWidgets.QLabel(self.widget)
        self.labelCampoCategoria.setObjectName("labelCampoCategoria")
        self.hlRegistrarNombreCategoria.addWidget(self.labelCampoCategoria)
        self.inputRegistrarCategoria = QtWidgets.QLineEdit(self.widget)
        self.inputRegistrarCategoria.setObjectName("inputRegistrarCategoria")
        self.hlRegistrarNombreCategoria.addWidget(self.inputRegistrarCategoria)
        self.tbOtraCategoria = QtWidgets.QToolButton(self.widget)
        self.tbOtraCategoria.setMinimumSize(QtCore.QSize(27, 0))
        self.tbOtraCategoria.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tbOtraCategoria.setObjectName("tbOtraCategoria")
        self.hlRegistrarNombreCategoria.addWidget(self.tbOtraCategoria)
        self.hRegistrarCamposTipoServicio.addLayout(self.hlRegistrarNombreCategoria)
        self.horizontalLayout_3.addLayout(self.hRegistrarCamposTipoServicio)
        self.botonRegistrarTipoServicio = QtWidgets.QPushButton(self.widget)
        self.botonRegistrarTipoServicio.setMinimumSize(QtCore.QSize(155, 32))
        self.botonRegistrarTipoServicio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonRegistrarTipoServicio.setIcon(icon2)
        self.botonRegistrarTipoServicio.setObjectName("botonRegistrarTipoServicio")
        self.horizontalLayout_3.addWidget(self.botonRegistrarTipoServicio)
        self.verticalLayout_15.addWidget(self.frameSuperiorTipoServicio)
        self.frameRegistrosTipoServicio = QtWidgets.QFrame(self.frameGeneralTipoServicio)
        self.frameRegistrosTipoServicio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRegistrosTipoServicio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRegistrosTipoServicio.setObjectName("frameRegistrosTipoServicio")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frameRegistrosTipoServicio)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.tvRegistrosTipoServicio = QtWidgets.QTableView(self.frameRegistrosTipoServicio)
        self.tvRegistrosTipoServicio.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tvRegistrosTipoServicio.setObjectName("tvRegistrosTipoServicio")
        self.tvRegistrosTipoServicio.verticalHeader().setVisible(False)
        self.verticalLayout_16.addWidget(self.tvRegistrosTipoServicio)
        self.verticalLayout_15.addWidget(self.frameRegistrosTipoServicio)
        self.frameInferiorTipoServicio = QtWidgets.QFrame(self.frameGeneralTipoServicio)
        self.frameInferiorTipoServicio.setMinimumSize(QtCore.QSize(0, 61))
        self.frameInferiorTipoServicio.setMaximumSize(QtCore.QSize(16777215, 61))
        self.frameInferiorTipoServicio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameInferiorTipoServicio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameInferiorTipoServicio.setObjectName("frameInferiorTipoServicio")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frameInferiorTipoServicio)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.botonRegresarSeccionTipoServicio = QtWidgets.QPushButton(self.frameInferiorTipoServicio)
        self.botonRegresarSeccionTipoServicio.setMinimumSize(QtCore.QSize(200, 35))
        self.botonRegresarSeccionTipoServicio.setMaximumSize(QtCore.QSize(200, 35))
        self.botonRegresarSeccionTipoServicio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonRegresarSeccionTipoServicio.setIcon(icon10)
        self.botonRegresarSeccionTipoServicio.setIconSize(QtCore.QSize(24, 24))
        self.botonRegresarSeccionTipoServicio.setObjectName("botonRegresarSeccionTipoServicio")
        self.verticalLayout_23.addWidget(self.botonRegresarSeccionTipoServicio, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_15.addWidget(self.frameInferiorTipoServicio)
        self.verticalLayout_9.addWidget(self.frameGeneralTipoServicio, 0, QtCore.Qt.AlignHCenter)
        self.ventanas.addWidget(self.paginaTiposServicio)
        self.paginaCategoriaTipoServicio = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paginaCategoriaTipoServicio.sizePolicy().hasHeightForWidth())
        self.paginaCategoriaTipoServicio.setSizePolicy(sizePolicy)
        self.paginaCategoriaTipoServicio.setMinimumSize(QtCore.QSize(1252, 0))
        self.paginaCategoriaTipoServicio.setObjectName("paginaCategoriaTipoServicio")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.paginaCategoriaTipoServicio)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frameGeneralCategoriaTipoServicio = QtWidgets.QFrame(self.paginaCategoriaTipoServicio)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameGeneralCategoriaTipoServicio.sizePolicy().hasHeightForWidth())
        self.frameGeneralCategoriaTipoServicio.setSizePolicy(sizePolicy)
        self.frameGeneralCategoriaTipoServicio.setMinimumSize(QtCore.QSize(1252, 685))
        self.frameGeneralCategoriaTipoServicio.setMaximumSize(QtCore.QSize(1252, 16777215))
        self.frameGeneralCategoriaTipoServicio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGeneralCategoriaTipoServicio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGeneralCategoriaTipoServicio.setObjectName("frameGeneralCategoriaTipoServicio")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frameGeneralCategoriaTipoServicio)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frameSuperiorCategoriaTipoServicio = QtWidgets.QFrame(self.frameGeneralCategoriaTipoServicio)
        self.frameSuperiorCategoriaTipoServicio.setMinimumSize(QtCore.QSize(876, 229))
        self.frameSuperiorCategoriaTipoServicio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameSuperiorCategoriaTipoServicio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSuperiorCategoriaTipoServicio.setObjectName("frameSuperiorCategoriaTipoServicio")
        self.labelTituloRegistrarCategoriaTipoServicio = QtWidgets.QLabel(self.frameSuperiorCategoriaTipoServicio)
        self.labelTituloRegistrarCategoriaTipoServicio.setGeometry(QtCore.QRect(330, 10, 591, 41))
        self.labelTituloRegistrarCategoriaTipoServicio.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTituloRegistrarCategoriaTipoServicio.setObjectName("labelTituloRegistrarCategoriaTipoServicio")
        self.lineaSeparadoraSeccionCategoriaTipoServicio = QtWidgets.QFrame(self.frameSuperiorCategoriaTipoServicio)
        self.lineaSeparadoraSeccionCategoriaTipoServicio.setGeometry(QtCore.QRect(0, 120, 1231, 20))
        self.lineaSeparadoraSeccionCategoriaTipoServicio.setFrameShape(QtWidgets.QFrame.HLine)
        self.lineaSeparadoraSeccionCategoriaTipoServicio.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lineaSeparadoraSeccionCategoriaTipoServicio.setObjectName("lineaSeparadoraSeccionCategoriaTipoServicio")
        self.layoutWidget_3 = QtWidgets.QWidget(self.frameSuperiorCategoriaTipoServicio)
        self.layoutWidget_3.setGeometry(QtCore.QRect(340, 80, 591, 34))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.hlRegistrarCategoriaTipoServicio = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.hlRegistrarCategoriaTipoServicio.setContentsMargins(0, 0, 0, 0)
        self.hlRegistrarCategoriaTipoServicio.setObjectName("hlRegistrarCategoriaTipoServicio")
        self.labelCampoCategoriaTipoServicio = QtWidgets.QLabel(self.layoutWidget_3)
        self.labelCampoCategoriaTipoServicio.setObjectName("labelCampoCategoriaTipoServicio")
        self.hlRegistrarCategoriaTipoServicio.addWidget(self.labelCampoCategoriaTipoServicio)
        self.inputRegistrarCategoriaTipoServicio = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.inputRegistrarCategoriaTipoServicio.setObjectName("inputRegistrarCategoriaTipoServicio")
        self.hlRegistrarCategoriaTipoServicio.addWidget(self.inputRegistrarCategoriaTipoServicio)
        self.botonRegistrarCategoriaTipoServicio = QtWidgets.QPushButton(self.layoutWidget_3)
        self.botonRegistrarCategoriaTipoServicio.setMinimumSize(QtCore.QSize(155, 32))
        self.botonRegistrarCategoriaTipoServicio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonRegistrarCategoriaTipoServicio.setIcon(icon2)
        self.botonRegistrarCategoriaTipoServicio.setObjectName("botonRegistrarCategoriaTipoServicio")
        self.hlRegistrarCategoriaTipoServicio.addWidget(self.botonRegistrarCategoriaTipoServicio)
        self.labelFiltroCategoriaTipoServicio = QtWidgets.QLabel(self.frameSuperiorCategoriaTipoServicio)
        self.labelFiltroCategoriaTipoServicio.setGeometry(QtCore.QRect(310, 200, 591, 20))
        self.labelFiltroCategoriaTipoServicio.setText("")
        self.labelFiltroCategoriaTipoServicio.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFiltroCategoriaTipoServicio.setObjectName("labelFiltroCategoriaTipoServicio")
        self.botonManualUsuarioSeccionCategoriaTipoServicio = QtWidgets.QPushButton(self.frameSuperiorCategoriaTipoServicio)
        self.botonManualUsuarioSeccionCategoriaTipoServicio.setGeometry(QtCore.QRect(1180, 10, 40, 40))
        self.botonManualUsuarioSeccionCategoriaTipoServicio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonManualUsuarioSeccionCategoriaTipoServicio.setStyleSheet("")
        self.botonManualUsuarioSeccionCategoriaTipoServicio.setText("")
        self.botonManualUsuarioSeccionCategoriaTipoServicio.setObjectName("botonManualUsuarioSeccionCategoriaTipoServicio")
        self.layoutWidget_4 = QtWidgets.QWidget(self.frameSuperiorCategoriaTipoServicio)
        self.layoutWidget_4.setGeometry(QtCore.QRect(350, 140, 431, 55))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.hlFiltroCategoriaTipoServicio = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.hlFiltroCategoriaTipoServicio.setContentsMargins(0, 0, 0, 0)
        self.hlFiltroCategoriaTipoServicio.setObjectName("hlFiltroCategoriaTipoServicio")
        self.vlFiltroCategoriaTipoServicio = QtWidgets.QVBoxLayout()
        self.vlFiltroCategoriaTipoServicio.setObjectName("vlFiltroCategoriaTipoServicio")
        self.labelFiltroSeccionCategoriaTipoServicio = QtWidgets.QLabel(self.layoutWidget_4)
        self.labelFiltroSeccionCategoriaTipoServicio.setObjectName("labelFiltroSeccionCategoriaTipoServicio")
        self.vlFiltroCategoriaTipoServicio.addWidget(self.labelFiltroSeccionCategoriaTipoServicio)
        self.inputFiltroSeccionCategoriaTipoServicio = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.inputFiltroSeccionCategoriaTipoServicio.setObjectName("inputFiltroSeccionCategoriaTipoServicio")
        self.vlFiltroCategoriaTipoServicio.addWidget(self.inputFiltroSeccionCategoriaTipoServicio)
        self.hlFiltroCategoriaTipoServicio.addLayout(self.vlFiltroCategoriaTipoServicio)
        self.botonRefrescarCategoriaTiposServicio = QtWidgets.QPushButton(self.frameSuperiorCategoriaTipoServicio)
        self.botonRefrescarCategoriaTiposServicio.setGeometry(QtCore.QRect(960, 170, 26, 24))
        self.botonRefrescarCategoriaTiposServicio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonRefrescarCategoriaTiposServicio.setStyleSheet("")
        self.botonRefrescarCategoriaTiposServicio.setText("")
        self.botonRefrescarCategoriaTiposServicio.setIcon(icon4)
        self.botonRefrescarCategoriaTiposServicio.setObjectName("botonRefrescarCategoriaTiposServicio")
        self.botonBuscarCategoriaTipoServicio = QtWidgets.QPushButton(self.frameSuperiorCategoriaTipoServicio)
        self.botonBuscarCategoriaTipoServicio.setGeometry(QtCore.QRect(790, 170, 148, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonBuscarCategoriaTipoServicio.sizePolicy().hasHeightForWidth())
        self.botonBuscarCategoriaTipoServicio.setSizePolicy(sizePolicy)
        self.botonBuscarCategoriaTipoServicio.setMinimumSize(QtCore.QSize(148, 30))
        self.botonBuscarCategoriaTipoServicio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonBuscarCategoriaTipoServicio.setIcon(icon3)
        self.botonBuscarCategoriaTipoServicio.setObjectName("botonBuscarCategoriaTipoServicio")
        self.verticalLayout_17.addWidget(self.frameSuperiorCategoriaTipoServicio)
        self.frameRegistrosCategoriaTipoServicio = QtWidgets.QFrame(self.frameGeneralCategoriaTipoServicio)
        self.frameRegistrosCategoriaTipoServicio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRegistrosCategoriaTipoServicio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRegistrosCategoriaTipoServicio.setObjectName("frameRegistrosCategoriaTipoServicio")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frameRegistrosCategoriaTipoServicio)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.tvRegistrosCategoriaTipoServicio = QtWidgets.QTableView(self.frameRegistrosCategoriaTipoServicio)
        self.tvRegistrosCategoriaTipoServicio.setObjectName("tvRegistrosCategoriaTipoServicio")
        self.tvRegistrosCategoriaTipoServicio.verticalHeader().setVisible(False)
        self.verticalLayout_18.addWidget(self.tvRegistrosCategoriaTipoServicio)
        self.verticalLayout_17.addWidget(self.frameRegistrosCategoriaTipoServicio)
        self.frameInferiorCategoriaTipoServicio = QtWidgets.QFrame(self.frameGeneralCategoriaTipoServicio)
        self.frameInferiorCategoriaTipoServicio.setMinimumSize(QtCore.QSize(0, 61))
        self.frameInferiorCategoriaTipoServicio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameInferiorCategoriaTipoServicio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameInferiorCategoriaTipoServicio.setObjectName("frameInferiorCategoriaTipoServicio")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frameInferiorCategoriaTipoServicio)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.botonRegresarSeccionCategoriaTipoServicio = QtWidgets.QPushButton(self.frameInferiorCategoriaTipoServicio)
        self.botonRegresarSeccionCategoriaTipoServicio.setMinimumSize(QtCore.QSize(200, 35))
        self.botonRegresarSeccionCategoriaTipoServicio.setMaximumSize(QtCore.QSize(200, 35))
        self.botonRegresarSeccionCategoriaTipoServicio.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botonRegresarSeccionCategoriaTipoServicio.setIcon(icon10)
        self.botonRegresarSeccionCategoriaTipoServicio.setIconSize(QtCore.QSize(24, 24))
        self.botonRegresarSeccionCategoriaTipoServicio.setObjectName("botonRegresarSeccionCategoriaTipoServicio")
        self.verticalLayout_24.addWidget(self.botonRegresarSeccionCategoriaTipoServicio, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_17.addWidget(self.frameInferiorCategoriaTipoServicio)
        self.verticalLayout_19.addWidget(self.frameGeneralCategoriaTipoServicio, 0, QtCore.Qt.AlignHCenter)
        self.ventanas.addWidget(self.paginaCategoriaTipoServicio)
        self.verticalLayout_10.addWidget(self.ventanas)

        self.retranslateUi(ventanaPrincipal)
        self.ventanas.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(ventanaPrincipal)

    def retranslateUi(self, ventanaPrincipal):
        _translate = QtCore.QCoreApplication.translate
        ventanaPrincipal.setWindowTitle(_translate("ventanaPrincipal", "Iniciar Sesión"))
        self.botonAcceder.setText(_translate("ventanaPrincipal", "Acceder"))
        self.labelTituloIniciarSesion.setText(_translate("ventanaPrincipal", "Iniciar Sesión"))
        self.labelNombreUsuario.setText(_translate("ventanaPrincipal", "Usuario"))
        self.inputNombreUsuario.setPlaceholderText(_translate("ventanaPrincipal", "Ingresa su usuario"))
        self.labelClaveUsuario.setText(_translate("ventanaPrincipal", "Contraseña"))
        self.inputClaveUsuario.setPlaceholderText(_translate("ventanaPrincipal", "Ingrese su contraseña"))
        self.botonManualUsuarioSeccionIniciarSesion.setToolTip(_translate("ventanaPrincipal", "<html><head/><body><p>Manual de usuario</p></body></html>"))
        self.labelDepartamento.setText(_translate("ventanaPrincipal", "Departamento:"))
        self.tbOtroDepartamento.setText(_translate("ventanaPrincipal", "..."))
        self.labelFallaPresenta.setText(_translate("ventanaPrincipal", "Falla que presenta:"))
        self.labelNombreTecnico.setText(_translate("ventanaPrincipal", "Nombre del técnico:"))
        self.labelServicioPrestado.setText(_translate("ventanaPrincipal", "Servicio prestado:"))
        self.tbOtroServicioPrestado.setText(_translate("ventanaPrincipal", "..."))
        self.labelDescripcion.setText(_translate("ventanaPrincipal", "Descripción:"))
        self.labelObservacionesAdicionales.setText(_translate("ventanaPrincipal", "Observaciones adicionales:"))
        self.labelFecha.setText(_translate("ventanaPrincipal", "Fecha:"))
        self.labelCantidad.setText(_translate("ventanaPrincipal", "Cantidad:"))
        self.botonManualUsuarioSeccionApp.setToolTip(_translate("ventanaPrincipal", "<html><head/><body><p>Manual de usuario</p></body></html>"))
        self.botonRegistrar.setText(_translate("ventanaPrincipal", " Registrar"))
        self.labelFiltroFecha.setText(_translate("ventanaPrincipal", "Fecha"))
        self.labelFiltroDepartamento.setText(_translate("ventanaPrincipal", "Departamento"))
        self.labelFiltroServicioPrestado.setText(_translate("ventanaPrincipal", "Servicio prestado"))
        self.botonBuscarServicios.setText(_translate("ventanaPrincipal", " Buscar"))
        self.botonRefrescarApp.setToolTip(_translate("ventanaPrincipal", "<html><head/><body><p>Refrescar</p></body></html>"))
        self.botonCrearUsuario.setText(_translate("ventanaPrincipal", " Gestión de usuarios"))
        self.botonCrearRespaldo.setText(_translate("ventanaPrincipal", " Crear respaldo"))
        self.botonImportarRespaldo.setText(_translate("ventanaPrincipal", " Importar respaldo"))
        self.botonGenerarReporte.setText(_translate("ventanaPrincipal", " Generar reporte"))
        self.botonCerrarSesion.setText(_translate("ventanaPrincipal", " Cerrar sesión"))
        self.botonRegistrarUsuario.setText(_translate("ventanaPrincipal", " Registrar"))
        self.labelTituloRegistrarUsuario.setText(_translate("ventanaPrincipal", "Crear nuevo usuario"))
        self.labelRegistrarNombreUsuario.setText(_translate("ventanaPrincipal", "Nombre de usuario:"))
        self.labelRegistrarRol.setText(_translate("ventanaPrincipal", "Rol:"))
        self.labelRegistrarClave.setText(_translate("ventanaPrincipal", "Contraseña:"))
        self.cbRolesRegistrarUsuario.setItemText(0, _translate("ventanaPrincipal", "ADMINISTRADOR"))
        self.cbRolesRegistrarUsuario.setItemText(1, _translate("ventanaPrincipal", "ESTANDAR"))
        self.botonRefrescarUsuarios.setToolTip(_translate("ventanaPrincipal", "<html><head/><body><p>Refrescar</p></body></html>"))
        self.botonManualUsuarioSeccionUsuarios.setToolTip(_translate("ventanaPrincipal", "<html><head/><body><p>Manual de usuario</p></body></html>"))
        self.botonRegresarSeccionUsuarios.setText(_translate("ventanaPrincipal", " Regresar"))
        self.labelTituloRegistrarDepartamento.setText(_translate("ventanaPrincipal", "Crear nuevo departamento"))
        self.labelNombreDepartamento.setText(_translate("ventanaPrincipal", "Nombre del departamento:"))
        self.botonRegistrarDepartamento.setText(_translate("ventanaPrincipal", "Registrar"))
        self.botonManualUsuarioSeccionDepartamentos.setToolTip(_translate("ventanaPrincipal", "<html><head/><body><p>Manual de usuario</p></body></html>"))
        self.botonBuscarDepartamento.setText(_translate("ventanaPrincipal", "Buscar"))
        self.botonRefrescarDepartamentos.setToolTip(_translate("ventanaPrincipal", "<html><head/><body><p>Refrescar</p></body></html>"))
        self.labelBuscarDepartamento.setText(_translate("ventanaPrincipal", "Departamento"))
        self.botonRegresarSeccionDepartamentos.setText(_translate("ventanaPrincipal", " Regresar"))
        self.labelTituloRegistrarTipoServicio.setText(_translate("ventanaPrincipal", "Crear nuevo tipo de servicio"))
        self.botonRefrescarTiposServicio.setToolTip(_translate("ventanaPrincipal", "<html><head/><body><p>Refrescar</p></body></html>"))
        self.botonManualUsuarioSeccionTipoServicio.setToolTip(_translate("ventanaPrincipal", "<html><head/><body><p>Manual de usuario</p></body></html>"))
        self.botonBuscarTipoServicio.setText(_translate("ventanaPrincipal", "Buscar"))
        self.labelFiltroTipoServicio.setText(_translate("ventanaPrincipal", "Tipo de servicio"))
        self.labelFiltroCategoria.setText(_translate("ventanaPrincipal", "Categoría"))
        self.labelCampoTipoServicio.setText(_translate("ventanaPrincipal", "Nombre del tipo de servicio:"))
        self.labelCampoCategoria.setText(_translate("ventanaPrincipal", "Categoría:"))
        self.tbOtraCategoria.setText(_translate("ventanaPrincipal", "..."))
        self.botonRegistrarTipoServicio.setText(_translate("ventanaPrincipal", " Registrar"))
        self.botonRegresarSeccionTipoServicio.setText(_translate("ventanaPrincipal", " Regresar"))
        self.labelTituloRegistrarCategoriaTipoServicio.setText(_translate("ventanaPrincipal", "Crear nueva categoría de tipo de servicio"))
        self.labelCampoCategoriaTipoServicio.setText(_translate("ventanaPrincipal", "Nombre de la categoría:"))
        self.botonRegistrarCategoriaTipoServicio.setText(_translate("ventanaPrincipal", " Registrar"))
        self.botonManualUsuarioSeccionCategoriaTipoServicio.setToolTip(_translate("ventanaPrincipal", "<html><head/><body><p>Manual de usuario</p></body></html>"))
        self.labelFiltroSeccionCategoriaTipoServicio.setText(_translate("ventanaPrincipal", "Categoría"))
        self.botonRefrescarCategoriaTiposServicio.setToolTip(_translate("ventanaPrincipal", "<html><head/><body><p>Refrescar</p></body></html>"))
        self.botonBuscarCategoriaTipoServicio.setText(_translate("ventanaPrincipal", "Buscar"))
        self.botonRegresarSeccionCategoriaTipoServicio.setText(_translate("ventanaPrincipal", " Regresar"))
import qtRecursosIconos_rc
import qtRecursosLogos_rc
