# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\vistas\vistas_qt\VentanaInfoCategoria.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VentanaInfoCategoria(object):
    def setupUi(self, VentanaInfoCategoria):
        VentanaInfoCategoria.setObjectName("VentanaInfoCategoria")
        VentanaInfoCategoria.resize(598, 268)
        VentanaInfoCategoria.setMinimumSize(QtCore.QSize(598, 268))
        VentanaInfoCategoria.setMaximumSize(QtCore.QSize(598, 268))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconos/iconos/icono-app-dgtic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        VentanaInfoCategoria.setWindowIcon(icon)
        VentanaInfoCategoria.setStyleSheet("#VentanaInfoCategoria {\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"#frameGeneralInfoCategoria .QPushButton{\n"
"    color: #ffffff;\n"
"    background-color: #417fd2;\n"
"    border: 1px solid rgb(0, 0, 0);\n"
"    border-radius: 6px;\n"
"    padding-bottom: 2px;\n"
"    font: 10pt \"Arial\";\n"
"}\n"
"\n"
"#frameGeneralInfoCategoria .QPushButton::hover{\n"
"    background-color: #5c8bc9;\n"
"}\n"
"\n"
"#frameGeneralInfoCategoria .QPushButton::pressed{\n"
"    background-color: #063c85;\n"
"}")
        self.frameGeneralInfoCategoria = QtWidgets.QFrame(VentanaInfoCategoria)
        self.frameGeneralInfoCategoria.setGeometry(QtCore.QRect(10, 10, 576, 246))
        self.frameGeneralInfoCategoria.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGeneralInfoCategoria.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGeneralInfoCategoria.setObjectName("frameGeneralInfoCategoria")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameGeneralInfoCategoria)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frameInfoCategoria = QtWidgets.QFrame(self.frameGeneralInfoCategoria)
        self.frameInfoCategoria.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameInfoCategoria.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameInfoCategoria.setObjectName("frameInfoCategoria")
        self.layoutWidget = QtWidgets.QWidget(self.frameInfoCategoria)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 70, 511, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.hlInfoCategoria = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.hlInfoCategoria.setContentsMargins(0, 0, 0, 0)
        self.hlInfoCategoria.setObjectName("hlInfoCategoria")
        self.labelInfoNombreCategoria = QtWidgets.QLabel(self.layoutWidget)
        self.labelInfoNombreCategoria.setObjectName("labelInfoNombreCategoria")
        self.hlInfoCategoria.addWidget(self.labelInfoNombreCategoria)
        self.inputInfoNombreCategoria = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputInfoNombreCategoria.setObjectName("inputInfoNombreCategoria")
        self.hlInfoCategoria.addWidget(self.inputInfoNombreCategoria)
        self.verticalLayout_2.addWidget(self.frameInfoCategoria)
        self.frameAccionesInfoCategoria = QtWidgets.QFrame(self.frameGeneralInfoCategoria)
        self.frameAccionesInfoCategoria.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameAccionesInfoCategoria.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameAccionesInfoCategoria.setObjectName("frameAccionesInfoCategoria")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frameAccionesInfoCategoria)
        self.layoutWidget_2.setGeometry(QtCore.QRect(30, 20, 481, 41))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.hlBotonesAccionCategoria = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.hlBotonesAccionCategoria.setContentsMargins(0, 0, 0, 0)
        self.hlBotonesAccionCategoria.setObjectName("hlBotonesAccionCategoria")
        self.botonAcualizarInfoCategoria = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonAcualizarInfoCategoria.sizePolicy().hasHeightForWidth())
        self.botonAcualizarInfoCategoria.setSizePolicy(sizePolicy)
        self.botonAcualizarInfoCategoria.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/iconos/iconos/icono-editar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonAcualizarInfoCategoria.setIcon(icon1)
        self.botonAcualizarInfoCategoria.setObjectName("botonAcualizarInfoCategoria")
        self.hlBotonesAccionCategoria.addWidget(self.botonAcualizarInfoCategoria)
        self.botonEliminarCategoria = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonEliminarCategoria.sizePolicy().hasHeightForWidth())
        self.botonEliminarCategoria.setSizePolicy(sizePolicy)
        self.botonEliminarCategoria.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/iconos/iconos/icono-eliminar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonEliminarCategoria.setIcon(icon2)
        self.botonEliminarCategoria.setObjectName("botonEliminarCategoria")
        self.hlBotonesAccionCategoria.addWidget(self.botonEliminarCategoria)
        self.botonCancelarInfoCategoria = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.botonCancelarInfoCategoria.sizePolicy().hasHeightForWidth())
        self.botonCancelarInfoCategoria.setSizePolicy(sizePolicy)
        self.botonCancelarInfoCategoria.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/iconos/iconos/icono-cancelar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botonCancelarInfoCategoria.setIcon(icon3)
        self.botonCancelarInfoCategoria.setObjectName("botonCancelarInfoCategoria")
        self.hlBotonesAccionCategoria.addWidget(self.botonCancelarInfoCategoria)
        self.verticalLayout_2.addWidget(self.frameAccionesInfoCategoria)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(1, 1)

        self.retranslateUi(VentanaInfoCategoria)
        QtCore.QMetaObject.connectSlotsByName(VentanaInfoCategoria)

    def retranslateUi(self, VentanaInfoCategoria):
        _translate = QtCore.QCoreApplication.translate
        VentanaInfoCategoria.setWindowTitle(_translate("VentanaInfoCategoria", "Información de la categoría"))
        self.labelInfoNombreCategoria.setText(_translate("VentanaInfoCategoria", "Nombre de la categoría:"))
        self.botonAcualizarInfoCategoria.setText(_translate("VentanaInfoCategoria", " Actualizar info"))
        self.botonEliminarCategoria.setText(_translate("VentanaInfoCategoria", " Eliminar"))
        self.botonCancelarInfoCategoria.setText(_translate("VentanaInfoCategoria", " Cancelar"))
import qtRecursosIconos_rc
